// Generated by tools/import-expansion.mjs. Edit research/expansion-*.json instead.
import type { LandmarkCategory, Region } from './types'
import type { LandmarkFacts } from './landmark-facts'
export interface ExpansionDesign { id: string; name: string; scope: Region; difficulty: 1|2|3; category: LandmarkCategory; modeled: boolean; confusables: string[] }
export const EXPANSION_DESIGN: readonly ExpansionDesign[] = [
  {
    "id": "kobe-port-tower",
    "name": "神戸ポートタワー",
    "scope": "japan",
    "difficulty": 2,
    "category": "tower",
    "modeled": true,
    "confusables": [
      "kyoto-tower",
      "eiffel-tower"
    ]
  },
  {
    "id": "naruto-whirlpools",
    "name": "鳴門の渦潮",
    "scope": "japan",
    "difficulty": 3,
    "category": "nature",
    "modeled": true,
    "confusables": [
      "nachi-falls",
      "megane-bridge",
      "kintaikyo",
      "tower-bridge"
    ]
  },
  {
    "id": "nachi-falls",
    "name": "那智の滝",
    "scope": "japan",
    "difficulty": 2,
    "category": "nature",
    "modeled": true,
    "confusables": [
      "naruto-whirlpools",
      "aogashima",
      "kiyomizudera",
      "mt-fuji",
      "iguazu-falls"
    ]
  },
  {
    "id": "aogashima",
    "name": "青ヶ島",
    "scope": "japan",
    "difficulty": 3,
    "category": "nature",
    "modeled": true,
    "confusables": [
      "mt-fuji",
      "mt-yotei",
      "machu-picchu",
      "mont-saint-michel"
    ]
  },
  {
    "id": "megane-bridge",
    "name": "眼鏡橋",
    "scope": "japan",
    "difficulty": 3,
    "category": "bridge",
    "modeled": true,
    "confusables": [
      "kintaikyo",
      "tower-bridge",
      "brooklyn-bridge",
      "kiyomizudera"
    ]
  },
  {
    "id": "amanohashidate",
    "name": "天橋立",
    "scope": "japan",
    "difficulty": 2,
    "category": "nature",
    "modeled": true,
    "confusables": [
      "aogashima",
      "naruto-whirlpools",
      "itsukushima",
      "mt-fuji"
    ]
  },
  {
    "id": "sazaedo",
    "name": "会津さざえ堂",
    "scope": "japan",
    "difficulty": 3,
    "category": "temple",
    "modeled": true,
    "confusables": [
      "nachi-falls",
      "kiyomizudera",
      "toshodaiji",
      "kinkakuji"
    ]
  },
  {
    "id": "daisen-kofun",
    "name": "大仙古墳",
    "scope": "japan",
    "difficulty": 2,
    "category": "tomb",
    "modeled": true,
    "confusables": [
      "goryokaku",
      "aogashima",
      "pyramids-giza",
      "chichen-itza"
    ]
  },
  {
    "id": "tojinbo",
    "name": "東尋坊",
    "scope": "japan",
    "difficulty": 3,
    "category": "nature",
    "modeled": true,
    "confusables": [
      "aogashima",
      "nachi-falls",
      "naruto-whirlpools"
    ]
  },
  {
    "id": "parthenon",
    "name": "パルテノン神殿",
    "scope": "world",
    "difficulty": 2,
    "category": "ruins",
    "modeled": true,
    "confusables": [
      "brandenburg-gate",
      "stonehenge",
      "petra",
      "colosseum"
    ]
  },
  {
    "id": "petra",
    "name": "ペトラ",
    "scope": "world",
    "difficulty": 2,
    "category": "ruins",
    "modeled": true,
    "confusables": [
      "abu-simbel",
      "parthenon",
      "machu-picchu",
      "borobudur"
    ]
  },
  {
    "id": "borobudur",
    "name": "ボロブドゥール",
    "scope": "world",
    "difficulty": 2,
    "category": "temple",
    "modeled": true,
    "confusables": [
      "angkor-wat",
      "chichen-itza",
      "machu-picchu",
      "taj-mahal"
    ]
  },
  {
    "id": "sagrada-familia",
    "name": "サグラダ・ファミリア",
    "scope": "world",
    "difficulty": 2,
    "category": "church",
    "modeled": true,
    "confusables": [
      "notre-dame",
      "mont-saint-michel",
      "neuschwanstein",
      "big-ben"
    ]
  },
  {
    "id": "aqueduct-segovia",
    "name": "セゴビアの水道橋",
    "scope": "world",
    "difficulty": 2,
    "category": "bridge",
    "modeled": true,
    "confusables": [
      "hadrians-wall",
      "colosseum",
      "tower-bridge",
      "brooklyn-bridge"
    ]
  },
  {
    "id": "great-zimbabwe",
    "name": "大ジンバブエ",
    "scope": "world",
    "difficulty": 3,
    "category": "ruins",
    "modeled": true,
    "confusables": [
      "stonehenge",
      "colosseum",
      "machu-picchu",
      "hadrians-wall"
    ]
  },
  {
    "id": "gonbad-e-qabus",
    "name": "ゴンバデ・カーブース",
    "scope": "world",
    "difficulty": 3,
    "category": "tomb",
    "modeled": true,
    "confusables": [
      "pisa-tower",
      "big-ben",
      "humayun-tomb",
      "great-zimbabwe"
    ]
  },
  {
    "id": "delicate-arch",
    "name": "デリケート・アーチ",
    "scope": "world",
    "difficulty": 3,
    "category": "nature",
    "modeled": true,
    "confusables": [
      "megane-bridge",
      "aqueduct-segovia",
      "stonehenge"
    ]
  },
  {
    "id": "iguazu-falls",
    "name": "イグアスの滝",
    "scope": "world",
    "difficulty": 2,
    "category": "nature",
    "modeled": true,
    "confusables": [
      "nachi-falls",
      "naruto-whirlpools",
      "aogashima"
    ]
  },
  {
    "id": "kinderdijk",
    "name": "キンデルダイクの風車群",
    "scope": "world",
    "difficulty": 2,
    "category": "village",
    "modeled": true,
    "confusables": [
      "shirakawago",
      "big-ben",
      "great-wall",
      "tsumagojuku"
    ]
  },
  {
    "id": "pasabag",
    "name": "パシャバーの奇岩群",
    "scope": "world",
    "difficulty": 3,
    "category": "nature",
    "modeled": true,
    "confusables": [
      "delicate-arch",
      "stonehenge",
      "pyramids-giza"
    ]
  },
  {
    "id": "temple-of-heaven",
    "name": "天壇・祈年殿",
    "scope": "world",
    "difficulty": 2,
    "category": "temple",
    "modeled": true,
    "confusables": [
      "forbidden-city",
      "angkor-wat",
      "borobudur",
      "blue-mosque"
    ]
  }
]
export const EXPANSION_FACTS: Readonly<Record<string, LandmarkFacts>> = {
  "kobe-port-tower": {
    "officialName": "神戸ポートタワー",
    "place": "兵庫県神戸市",
    "lat": 34.6825,
    "lon": 135.1867,
    "built": "",
    "fact": "屋上デッキから神戸の街と港を360度見渡せる。",
    "factSources": [
      {
        "title": "神戸ポートタワー公式：フロアガイド",
        "url": "https://www.kobe-port-tower.com/",
        "checkedAt": "2026-10-04"
      }
    ]
  },
  "naruto-whirlpools": {
    "officialName": "鳴門の渦潮",
    "place": "徳島県鳴門市・兵庫県南あわじ市",
    "lat": 34.238,
    "lon": 134.647,
    "built": "自然地形",
    "fact": "渦潮には見頃の時間があり、大潮ほど大きな渦が期待できる。",
    "factSources": [
      {
        "title": "うずしお観潮船公式：渦潮の見頃・大潮",
        "url": "https://www.uzusio.com/",
        "checkedAt": "2026-10-04"
      },
      {
        "title": "うずしお観潮船公式：鳴門のうずしお",
        "url": "https://www.uzusio.com/know/",
        "checkedAt": "2026-10-04"
      }
    ]
  },
  "nachi-falls": {
    "officialName": "那智の滝",
    "place": "和歌山県那智勝浦町",
    "lat": 33.675,
    "lon": 135.887,
    "built": "自然地形",
    "fact": "落差133m。滝そのものが信仰の対象になっている。",
    "factSources": [
      {
        "title": "和歌山県公式観光：All of the sights of Nachi Falls",
        "url": "https://visitwakayama.jp/en/stories/detail_539.html",
        "checkedAt": "2026-10-04"
      }
    ]
  },
  "aogashima": {
    "officialName": "青ヶ島",
    "place": "東京都青ヶ島村",
    "lat": 32.458,
    "lon": 139.767,
    "built": "自然地形",
    "fact": "二重カルデラを展望できる東京都の火山島。",
    "factSources": [
      {
        "title": "東京都：東京宝島うみそら便 青ヶ島",
        "url": "https://www.islandaccess.metro.tokyo.lg.jp/island/aogashima/",
        "checkedAt": "2026-10-04"
      }
    ]
  },
  "megane-bridge": {
    "officialName": "眼鏡橋",
    "place": "長崎県長崎市",
    "lat": 32.747,
    "lon": 129.882,
    "built": "1634年",
    "fact": "1634年架設。川面に映る双円が眼鏡に見える石橋。",
    "factSources": [
      {
        "title": "長崎県観光連盟：眼鏡橋",
        "url": "https://www.nagasaki-tabinet.com/guide/95",
        "checkedAt": "2026-10-04"
      }
    ]
  },
  "amanohashidate": {
    "officialName": "天橋立",
    "place": "京都府宮津市",
    "lat": 35.57,
    "lon": 135.19,
    "built": "自然地形",
    "fact": "宮津湾に延びる全長約3.6kmの松の砂州。",
    "factSources": [
      {
        "title": "天橋立観光協会：天橋立",
        "url": "https://www.amanohashidate.jp/spot/amanohashidate/",
        "checkedAt": "2026-10-04"
      }
    ]
  },
  "sazaedo": {
    "officialName": "円通三匝堂（会津さざえ堂）",
    "place": "福島県会津若松市",
    "lat": 37.504,
    "lon": 139.953,
    "built": "1796年",
    "fact": "1796年建立。六角の木造堂内に二重らせんの通路がある。",
    "factSources": [
      {
        "title": "東北観光推進機構：Aizu Sazaedo",
        "url": "https://www.tohokukanko.jp/en/attractions/detail_1057.html",
        "checkedAt": "2026-10-04"
      },
      {
        "title": "福島県観光：5 Reasons to Visit Sazaedo Temple",
        "url": "https://fukushima.travel/blogs/5-reasons-to-visit-sazaedo-temple/71",
        "checkedAt": "2026-10-04"
      }
    ]
  },
  "daisen-kofun": {
    "officialName": "仁徳天皇陵古墳（大山古墳）",
    "place": "大阪府堺市",
    "lat": 34.565,
    "lon": 135.488,
    "built": "",
    "fact": "三重の濠をめぐらせた全長約486mの前方後円墳。",
    "factSources": [
      {
        "title": "堺市：仁徳天皇陵古墳（大山古墳）",
        "url": "https://www.city.sakai.lg.jp/kanko/rekishi/dkofun/database/nintokutenno.html",
        "checkedAt": "2026-10-04"
      }
    ]
  },
  "tojinbo": {
    "officialName": "東尋坊",
    "place": "福井県坂井市",
    "lat": 36.238,
    "lon": 136.126,
    "built": "自然地形",
    "fact": "日本海の波が削った、五・六角柱の岩が並ぶ海岸。",
    "factSources": [
      {
        "title": "坂井市観光：Tojinbo and Oshima Island",
        "url": "https://kanko-sakai.com/en/feature/tojinbo_oshima/",
        "checkedAt": "2026-10-04"
      }
    ]
  },
  "parthenon": {
    "officialName": "パルテノン神殿",
    "place": "ギリシャ・アテネ",
    "lat": 37.9715,
    "lon": 23.7266,
    "built": "紀元前447年着工、約15年間で完成",
    "fact": "アテーナーに捧げられた白大理石の神殿。",
    "factSources": [
      {
        "title": "Acropolis Museum: The Parthenon Gallery",
        "url": "https://www.theacropolismuseum.gr/en/exhibit-halls/parthenon-gallery",
        "checkedAt": "2026-10-04"
      }
    ]
  },
  "petra": {
    "officialName": "ペトラ（アル・ハズネ）",
    "place": "ヨルダン・ワディムーサ",
    "lat": 30.328611,
    "lon": 35.441944,
    "built": "紀元前1世紀末〜紀元1世紀ごろ（推定）",
    "fact": "アル・ハズネは岩を彫って造られた墓廟。",
    "factSources": [
      {
        "title": "Petra Development and Tourism Region Authority: Al Khazna (The Treasury)",
        "url": "https://www.visitpetra.jo/en/Location/2",
        "checkedAt": "2026-10-04"
      },
      {
        "title": "UNESCO: Petra",
        "url": "https://whc.unesco.org/en/list/326/",
        "checkedAt": "2026-10-04"
      }
    ]
  },
  "borobudur": {
    "officialName": "ボロブドゥール寺院",
    "place": "インドネシア・中部ジャワ",
    "lat": -7.607778,
    "lon": 110.203889,
    "built": "8〜9世紀",
    "fact": "円形壇に鐘形ストゥーパが並ぶ仏教寺院。",
    "factSources": [
      {
        "title": "UNESCO: Borobudur Temple Compounds",
        "url": "https://whc.unesco.org/en/list/592/",
        "checkedAt": "2026-10-04"
      },
      {
        "title": "InJourney Destination: Borobudur Temple",
        "url": "https://injourneydestination.id/en/destinations/borobudur/",
        "checkedAt": "2026-10-04"
      }
    ]
  },
  "sagrada-familia": {
    "officialName": "サグラダ・ファミリア聖堂",
    "place": "スペイン・バルセロナ",
    "lat": 41.4036,
    "lon": 2.1744,
    "built": "1882年着工",
    "fact": "1883年からガウディが設計を引き継いだ。",
    "factSources": [
      {
        "title": "Sagrada Família: History of the Temple",
        "url": "https://sagradafamilia.org/en/history-of-the-temple",
        "checkedAt": "2026-10-04"
      }
    ]
  },
  "aqueduct-segovia": {
    "officialName": "セゴビアのローマ水道橋",
    "place": "スペイン・セゴビア",
    "lat": 40.948472,
    "lon": -4.11675,
    "built": "古代ローマ時代",
    "fact": "上下二段のアーチが重なるローマ水道橋。",
    "factSources": [
      {
        "title": "UNESCO: Old Town of Segovia and its Aqueduct",
        "url": "https://whc.unesco.org/en/list/311/",
        "checkedAt": "2026-10-04"
      }
    ]
  },
  "great-zimbabwe": {
    "officialName": "大ジンバブエ遺跡",
    "place": "ジンバブエ・マシンゴ近郊",
    "lat": -20.27117,
    "lon": 30.933269,
    "built": "11〜15世紀（大囲壁は14世紀）",
    "fact": "楕円の大囲壁には高い円錐塔が残る。",
    "factSources": [
      {
        "title": "UNESCO: Great Zimbabwe National Monument",
        "url": "https://whc.unesco.org/en/list/364/",
        "checkedAt": "2026-10-04"
      }
    ]
  },
  "gonbad-e-qabus": {
    "officialName": "ゴンバデ・カーブース",
    "place": "イラン・ゴンバデ・カーブース",
    "lat": 37.258028,
    "lon": 55.169,
    "built": "1006年",
    "fact": "十角星の平面を持つ、円錐屋根の煉瓦墓塔。",
    "factSources": [
      {
        "title": "UNESCO: Gonbad-e Qābus",
        "url": "https://whc.unesco.org/en/list/1398/",
        "checkedAt": "2026-10-04"
      }
    ]
  },
  "delicate-arch": {
    "officialName": "デリケート・アーチ",
    "place": "アメリカ合衆国ユタ州・アーチーズ国立公園",
    "lat": 38.7436,
    "lon": -109.4993,
    "built": "自然地形",
    "fact": "独立した自然の岩門がユタ州の象徴。",
    "factSources": [
      {
        "title": "U.S. National Park Service: Delicate Arch",
        "url": "https://home.nps.gov/arch/planyourvisit/delicate-arch.htm",
        "checkedAt": "2026-10-04"
      }
    ]
  },
  "iguazu-falls": {
    "officialName": "イグアスの滝",
    "place": "アルゼンチン・ミシオネス州／ブラジルとの国境",
    "lat": -25.6867,
    "lon": -54.4449,
    "built": "自然地形",
    "fact": "国境の森に囲まれ、幾つもの滝が連なる。",
    "factSources": [
      {
        "title": "Administración de Parques Nacionales: Parque Nacional Iguazú",
        "url": "https://www.argentina.gob.ar/parquesnacionales/nea/parque-nacional-iguazu",
        "checkedAt": "2026-10-04"
      },
      {
        "title": "Administración de Parques Nacionales: Actividades",
        "url": "https://www.argentina.gob.ar/parquesnacionales/nea/parque-nacional-iguazu/actividades",
        "checkedAt": "2026-10-04"
      },
      {
        "title": "Iguazú Argentina: Circuito Garganta del Diablo（公式運営者）",
        "url": "https://iguazuargentina.com/area-cataratas/circuito-garganta/",
        "checkedAt": "2026-10-04"
      },
      {
        "title": "Iguazú Argentina: Circuito Inferior（公式本文と写真観察）",
        "url": "https://iguazuargentina.com/area-cataratas/circuito-inferior/",
        "checkedAt": "2026-10-04"
      },
      {
        "title": "Iguazú Argentina: Circuito Superior（公式本文と写真観察）",
        "url": "https://iguazuargentina.com/area-cataratas/circuito-superior/",
        "checkedAt": "2026-10-04"
      }
    ]
  },
  "kinderdijk": {
    "officialName": "キンデルダイク＝エルスハウトの風車群",
    "place": "オランダ・南ホラント州",
    "lat": 51.8825,
    "lon": 4.649444,
    "built": "主な排水風車は1738年・1740年",
    "fact": "19基の排水風車が低地の水管理を伝える。",
    "factSources": [
      {
        "title": "UNESCO: Mill Network at Kinderdijk-Elshout",
        "url": "https://whc.unesco.org/en/list/818/",
        "checkedAt": "2026-10-04"
      },
      {
        "title": "Kinderdijk: UNESCO World Heritage（公式運営者）",
        "url": "https://kinderdijk.nl/en/unesco-world-heritage/",
        "checkedAt": "2026-10-04"
      }
    ]
  },
  "pasabag": {
    "officialName": "パシャバー（Paşabağ）の奇岩群",
    "place": "トルコ・カッパドキア",
    "lat": 38.679,
    "lon": 34.853,
    "built": "自然地形",
    "fact": "円錐形の岩柱に硬い岩の帽子が載る。",
    "factSources": [
      {
        "title": "GoTürkiye: Top Things to See in Cappadocia — Paşabağ",
        "url": "https://goturkiye.com/cappadocia/see-cappadocia",
        "checkedAt": "2026-10-04"
      }
    ]
  },
  "temple-of-heaven": {
    "officialName": "天壇（祈年殿 / Hall of Prayer for Good Harvests）",
    "place": "中国・北京市",
    "lat": 39.882167,
    "lon": 116.406667,
    "built": "天壇は1420年成立、後世に再建",
    "fact": "明清の皇帝が天を祀り豊作を祈った。",
    "factSources": [
      {
        "title": "UNESCO: Temple du Ciel, autel sacrificiel impérial à Beijing（フランス語本文）",
        "url": "https://whc.unesco.org/fr/list/881/",
        "checkedAt": "2026-10-04"
      }
    ]
  }
}
