// 名所の「調べて確かめる値」（正式名・場所・緯度経度・完成の年・豆知識・出典）。ゲームの設計の値（難しさ・種類・
// 見間違えやすい名所）は landmarks.ts に分けてある。
//
// ⚠️ このファイルは tools/import-facts.mjs が research/landmarks.json から作る。手で直さない。
//    初期24件は2026-10-01にWikipediaで照合。追加24件は2026-10-03に公式資料で照合（research/README.md）。

import { EXPANSION_FACTS } from './expansion-catalog'
import type { FactSource } from './types'

export interface LandmarkFacts {
  officialName: string
  place: string
  lat: number
  lon: number
  /** 完成・建立の年（例：1958年）。わからなければ空文字 */
  built: string
  fact: string
  factSources: FactSource[]
}

export const FACTS_STATUS: 'provisional' | 'researched' = 'researched'

const LEGACY_FACTS: Readonly<Record<string, LandmarkFacts>> = {
  kinkakuji: {
    officialName: "鹿苑寺（北山鹿苑禅寺）",
    place: "京都府京都市",
    lat: 35.0394,
    lon: 135.7294,
    built: "1955年（舎利殿の再建。北山山荘の造営は1397年）",
    fact: "今の金閣（舎利殿）は1955年の再建。元の建物は1950年に放火で焼けた。",
    factSources: [{ title: "ウィキペディア日本語版「鹿苑寺」", url: "https://ja.wikipedia.org/wiki/%E9%B9%BF%E8%8B%91%E5%AF%BA" }],
  },
  itsukushima: {
    officialName: "嚴島神社 大鳥居",
    place: "広島県廿日市市",
    lat: 34.2973,
    lon: 132.3182,
    built: "1875年（今の鳥居の再建）",
    fact: "今の大鳥居は1875年の再建で、9代目だと近年の研究でわかった。",
    factSources: [{ title: "ウィキペディア日本語版「厳島神社大鳥居」", url: "https://ja.wikipedia.org/wiki/%E5%8E%B3%E5%B3%B6%E7%A5%9E%E7%A4%BE%E5%A4%A7%E9%B3%A5%E5%B1%85" }],
  },
  "mt-fuji": {
    officialName: "富士山",
    place: "静岡県・山梨県",
    lat: 35.3606,
    lon: 138.7275,
    built: "（自然の山）",
    fact: "山梨県と静岡県にまたがる日本最高峰。2013年に世界文化遺産に登録された。",
    factSources: [{ title: "ウィキペディア日本語版「富士山」", url: "https://ja.wikipedia.org/wiki/%E5%AF%8C%E5%A3%AB%E5%B1%B1" }],
  },
  "himeji-castle": {
    officialName: "姫路城",
    place: "兵庫県姫路市",
    lat: 34.8394,
    lon: 134.6936,
    built: "1601〜1609年（池田輝政の大改修で今の姿に）",
    fact: "別名は白鷺城。江戸時代初期の天守が残る現存12天守の一つで世界遺産。",
    factSources: [{ title: "ウィキペディア日本語版「姫路城」", url: "https://ja.wikipedia.org/wiki/%E5%A7%AB%E8%B7%AF%E5%9F%8E" }],
  },
  "osaka-castle": {
    officialName: "大坂城（大阪城）",
    place: "大阪府大阪市",
    lat: 34.6872,
    lon: 135.5258,
    built: "1931年（今の天守の復興）",
    fact: "今の天守は1931年に鉄骨鉄筋コンクリートで復興されたもの。",
    factSources: [{ title: "ウィキペディア日本語版「大坂城」", url: "https://ja.wikipedia.org/wiki/%E5%A4%A7%E5%9D%82%E5%9F%8E" }],
  },
  kaminarimon: {
    officialName: "風雷神門（浅草寺 雷門）",
    place: "東京都台東区",
    lat: 35.7111,
    lon: 139.7963,
    built: "1960年（今の門の再建）",
    fact: "正式名は風雷神門。中央の提灯は高さ3.9メートル、直径3.3メートル。",
    factSources: [{ title: "ウィキペディア日本語版「雷門」", url: "https://ja.wikipedia.org/wiki/%E9%9B%B7%E9%96%80" }],
  },
  kiyomizudera: {
    officialName: "音羽山 清水寺",
    place: "京都府京都市",
    lat: 34.9948,
    lon: 135.785,
    built: "1633年（今の本堂の再建）",
    fact: "舞台を支えるケヤキの柱は139本といわれ、釘は使われていない。",
    factSources: [{ title: "ウィキペディア日本語版「清水寺」", url: "https://ja.wikipedia.org/wiki/%E6%B8%85%E6%B0%B4%E5%AF%BA" }],
  },
  todaiji: {
    officialName: "東大寺 金堂（大仏殿）",
    place: "奈良県奈良市",
    lat: 34.689,
    lon: 135.8399,
    built: "1709年（今の大仏殿）",
    fact: "今の大仏殿は1709年の完成で、幅は創建時の約3分の2になっている。",
    factSources: [{ title: "ウィキペディア日本語版「東大寺大仏殿」", url: "https://ja.wikipedia.org/wiki/%E6%9D%B1%E5%A4%A7%E5%AF%BA%E5%A4%A7%E4%BB%8F%E6%AE%BF" }],
  },
  "fushimi-inari": {
    officialName: "伏見稲荷大社 千本鳥居",
    place: "京都府京都市",
    lat: 34.9672,
    lon: 135.7734,
    built: "江戸時代から（鳥居の奉納が始まる）",
    fact: "鳥居を奉納する習わしは江戸時代に始まり、山中に約1万基あるという。",
    factSources: [{ title: "ウィキペディア日本語版「伏見稲荷大社」", url: "https://ja.wikipedia.org/wiki/%E4%BC%8F%E8%A6%8B%E7%A8%B2%E8%8D%B7%E5%A4%A7%E7%A4%BE" }],
  },
  shirakawago: {
    officialName: "白川郷・五箇山の合掌造り集落（荻町集落）",
    place: "岐阜県白川村",
    lat: 36.2583,
    lon: 136.9056,
    built: "江戸時代末期〜明治時代末期（荻町の合掌造り家屋）",
    fact: "1995年に五箇山とともに世界遺産に。荻町の合掌造りは今も暮らしの場。",
    factSources: [{ title: "ウィキペディア日本語版「白川郷」", url: "https://ja.wikipedia.org/wiki/%E7%99%BD%E5%B7%9D%E9%83%B7" }],
  },
  goryokaku: {
    officialName: "五稜郭（特別史跡 五稜郭跡）",
    place: "北海道函館市",
    lat: 41.7969,
    lon: 140.7569,
    built: "1866年",
    fact: "1866年完成の星形の城郭。完成からわずか2年後に江戸幕府が崩壊した。",
    factSources: [{ title: "ウィキペディア日本語版「五稜郭」", url: "https://ja.wikipedia.org/wiki/%E4%BA%94%E7%A8%9C%E9%83%AD" }],
  },
  "pyramids-giza": {
    officialName: "ギザの三大ピラミッド（ギザの大スフィンクスを含む）",
    place: "エジプト・ギザ",
    lat: 29.9792,
    lon: 31.1342,
    built: "紀元前2500年ごろ",
    fact: "スフィンクスは全長73.5m。一枚岩から彫った像として世界最大。",
    factSources: [{ title: "ウィキペディア日本語版「ギザの大スフィンクス」", url: "https://ja.wikipedia.org/wiki/%E3%82%AE%E3%82%B6%E3%81%AE%E5%A4%A7%E3%82%B9%E3%83%95%E3%82%A3%E3%83%B3%E3%82%AF%E3%82%B9" }],
  },
  "eiffel-tower": {
    officialName: "エッフェル塔（La tour Eiffel）",
    place: "フランス・パリ",
    lat: 48.8583,
    lon: 2.2945,
    built: "1889年",
    fact: "1889年のパリ万博に合わせて建設。名前は設計・建設者のエッフェルから。",
    factSources: [{ title: "ウィキペディア日本語版「エッフェル塔」", url: "https://ja.wikipedia.org/wiki/%E3%82%A8%E3%83%83%E3%83%95%E3%82%A7%E3%83%AB%E5%A1%94" }],
  },
  "pisa-tower": {
    officialName: "ピサの斜塔（ピサ大聖堂の鐘楼）",
    place: "イタリア・ピサ",
    lat: 43.723,
    lon: 10.3966,
    built: "1372年（1173年着工）",
    fact: "ピサ大聖堂の鐘楼で、高さは地上55.86m、階段は296段ある。",
    factSources: [{ title: "ウィキペディア日本語版「ピサの斜塔」", url: "https://ja.wikipedia.org/wiki/%E3%83%94%E3%82%B5%E3%81%AE%E6%96%9C%E5%A1%94" }],
  },
  "statue-of-liberty": {
    officialName: "世界を照らす自由（自由の女神像）",
    place: "アメリカ・ニューヨーク",
    lat: 40.6892,
    lon: -74.0444,
    built: "1886年",
    fact: "米国独立100周年を記念し、フランス人の募金で贈られた像。",
    factSources: [{ title: "ウィキペディア日本語版「自由の女神像 (ニューヨーク)」", url: "https://ja.wikipedia.org/wiki/%E8%87%AA%E7%94%B1%E3%81%AE%E5%A5%B3%E7%A5%9E%E5%83%8F_%28%E3%83%8B%E3%83%A5%E3%83%BC%E3%83%A8%E3%83%BC%E3%82%AF%29" }],
  },
  colosseum: {
    officialName: "コロッセウム（フラウィウス円形闘技場）",
    place: "イタリア・ローマ",
    lat: 41.8903,
    lon: 12.4922,
    built: "80年",
    fact: "西暦80年に造られた円形闘技場。当時の正式名はフラウィウス円形闘技場。",
    factSources: [{ title: "ウィキペディア日本語版「コロッセウム」", url: "https://ja.wikipedia.org/wiki/%E3%82%B3%E3%83%AD%E3%83%83%E3%82%BB%E3%82%A6%E3%83%A0" }],
  },
  "taj-mahal": {
    officialName: "タージ・マハル",
    place: "インド・アーグラ",
    lat: 27.175,
    lon: 78.0419,
    built: "1653年（1632年着工）",
    fact: "皇帝シャー・ジャハーンが亡き妃のために建てた総大理石の墓廟。",
    factSources: [{ title: "ウィキペディア日本語版「タージ・マハル」", url: "https://ja.wikipedia.org/wiki/%E3%82%BF%E3%83%BC%E3%82%B8%E3%83%BB%E3%83%9E%E3%83%8F%E3%83%AB" }],
  },
  "great-wall": {
    officialName: "万里の長城（地点は八達嶺長城）",
    place: "中国・北京市（八達嶺）",
    lat: 40.3543,
    lon: 116.0065,
    built: "紀元前214年に建設開始（今の大部分は明代）",
    fact: "現存する壁の長さは6,259.7km。大部分は明代に造られた。",
    factSources: [{ title: "ウィキペディア日本語版「万里の長城」", url: "https://ja.wikipedia.org/wiki/%E4%B8%87%E9%87%8C%E3%81%AE%E9%95%B7%E5%9F%8E" }],
  },
  "big-ben": {
    officialName: "エリザベス・タワー（ビッグ・ベン）",
    place: "イギリス・ロンドン",
    lat: 51.5007,
    lon: -0.1246,
    built: "1859年（時計塔の完成）",
    fact: "本来は時計塔の大きな鐘の愛称。塔は2012年にエリザベスタワーと命名。",
    factSources: [{ title: "ウィキペディア日本語版「ビッグ・ベン」", url: "https://ja.wikipedia.org/wiki/%E3%83%93%E3%83%83%E3%82%B0%E3%83%BB%E3%83%99%E3%83%B3" }],
  },
  moai: {
    officialName: "アフ・トンガリキのモアイ",
    place: "チリ・イースター島",
    lat: -27.1258,
    lon: -109.2769,
    built: "1100〜1600年ごろ（モアイの製造）。1990年代に修復",
    fact: "島内最大のアフに15体のモアイが並ぶ。修復に日本のタダノが協力した。",
    factSources: [{ title: "ウィキペディア日本語版「アフ・トンガリキ」", url: "https://ja.wikipedia.org/wiki/%E3%82%A2%E3%83%95%E3%83%BB%E3%83%88%E3%83%B3%E3%82%AC%E3%83%AA%E3%82%AD" }],
  },
  stonehenge: {
    officialName: "ストーンヘンジ",
    place: "イギリス・ウィルトシャー",
    lat: 51.1789,
    lon: -1.8261,
    built: "紀元前2500〜紀元前2000年（巨石を立てた時期）",
    fact: "夏至の日、ヒール・ストーンと祭壇石を結ぶ線上に太陽が昇る。",
    factSources: [{ title: "ウィキペディア日本語版「ストーンヘンジ」", url: "https://ja.wikipedia.org/wiki/%E3%82%B9%E3%83%88%E3%83%BC%E3%83%B3%E3%83%98%E3%83%B3%E3%82%B8" }],
  },
  neuschwanstein: {
    officialName: "ノイシュヴァンシュタイン城",
    place: "ドイツ・シュヴァンガウ（バイエルン州）",
    lat: 47.5575,
    lon: 10.7494,
    built: "1869〜1886年と1890〜1892年（未完成のまま工事を終えた）",
    fact: "名前はドイツ語で「新白鳥石」。バイエルン王ルートヴィヒ2世が建てた。",
    factSources: [{ title: "ウィキペディア日本語版「ノイシュヴァンシュタイン城」", url: "https://ja.wikipedia.org/wiki/%E3%83%8E%E3%82%A4%E3%82%B7%E3%83%A5%E3%83%B4%E3%82%A1%E3%83%B3%E3%82%B7%E3%83%A5%E3%82%BF%E3%82%A4%E3%83%B3%E5%9F%8E" }],
  },
  "tower-bridge": {
    officialName: "タワーブリッジ",
    place: "イギリス・ロンドン",
    lat: 51.5056,
    lon: -0.0753,
    built: "1894年（1886年着工）",
    fact: "1894年完成の跳開橋。名前の「タワー」は近くのロンドン塔から。",
    factSources: [{ title: "ウィキペディア日本語版「タワーブリッジ」", url: "https://ja.wikipedia.org/wiki/%E3%82%BF%E3%83%AF%E3%83%BC%E3%83%96%E3%83%AA%E3%83%83%E3%82%B8" }],
  },
  "kobe-port-tower": {
    officialName: "神戸ポートタワー",
    place: "兵庫県神戸市",
    lat: 34.6825,
    lon: 135.1867,
    built: "1963年",
    fact: "1963年開業。鼓形の外観から「鉄塔の美女」とも呼ばれる。",
    factSources: [{ title: "ウィキペディア日本語版「神戸ポートタワー」", url: "https://ja.wikipedia.org/wiki/%E7%A5%9E%E6%88%B8%E3%83%9D%E3%83%BC%E3%83%88%E3%82%BF%E3%83%AF%E3%83%BC" }],
  },
  "kyoto-tower": {
    officialName: "京都タワー（ニデック京都タワー）",
    place: "京都府京都市",
    lat: 34.9875,
    lon: 135.7594,
    built: "",
    fact: "",
    factSources: [],
  },
  ginkakuji: {
    officialName: "慈照寺（東山慈照禅寺）",
    place: "京都府京都市",
    lat: 35.0269,
    lon: 135.7983,
    built: "",
    fact: "二層の銀閣と、白砂を盛った向月台が庭園の名物。",
    factSources: [{ title: "銀閣寺公式：境内案内", url: "https://www.shokoku-ji.jp/ginkakuji/guide/" }],
  },
  byodoin: {
    officialName: "平等院 鳳凰堂",
    place: "京都府宇治市",
    lat: 34.8893,
    lon: 135.8077,
    built: "",
    fact: "鳳凰堂は中堂、左右の翼廊、背後の尾廊からなる。",
    factSources: [{ title: "平等院公式：日本語パンフレット", url: "https://www.byodoin.or.jp/common/pdf/pamphlet-ja.pdf" }],
  },
  toshodaiji: {
    officialName: "唐招提寺",
    place: "奈良県奈良市",
    lat: 34.6756,
    lon: 135.7848,
    built: "8世紀後半（今の金堂）",
    fact: "金堂は正面七間、奥行き四間の寄棟造。",
    factSources: [{ title: "唐招提寺公式：金堂", url: "https://www.toshodaiji.jp/about_kondoh.html" }],
  },
  hasedera: {
    officialName: "長谷寺",
    place: "奈良県桜井市",
    lat: 34.5359,
    lon: 135.9068,
    built: "",
    fact: "",
    factSources: [],
  },
  "matsumoto-castle": {
    officialName: "松本城",
    place: "長野県松本市",
    lat: 36.2391,
    lon: 137.9691,
    built: "",
    fact: "外からは五重に見えるが、大天守の内部は六階ある。",
    factSources: [{ title: "松本城公式：天守とその構造", url: "https://www.matsumoto-castle.jp/about/tower" }],
  },
  "kumamoto-castle": {
    officialName: "熊本城",
    place: "熊本県熊本市",
    lat: 32.806,
    lon: 130.7059,
    built: "",
    fact: "並び立つ大小の天守は2021年に完全復旧した。",
    factSources: [{ title: "熊本城公式：熊本城紹介", url: "https://castle.kumamoto-guide.jp/about/" }],
  },
  "nagoya-castle": {
    officialName: "名古屋城",
    place: "愛知県名古屋市",
    lat: 35.1855,
    lon: 136.8991,
    built: "",
    fact: "大天守の金鯱は北が雄、南が雌の一対になっている。",
    factSources: [{ title: "名古屋城公式：金鯱", url: "https://www.nagoyajo.city.nagoya.jp/guide/kinshachi/" }],
  },
  "izumo-taisha": {
    officialName: "出雲大社（いずもおおやしろ）",
    place: "島根県出雲市",
    lat: 35.4019,
    lon: 132.6854,
    built: "1744年（今の本殿）",
    fact: "神楽殿の大注連縄は長さ約13m、重さ5.2t。",
    factSources: [{ title: "出雲大社公式：神楽殿", url: "https://izumooyashiro.or.jp/kaguraden" }],
  },
  "heian-jingu": {
    officialName: "平安神宮",
    place: "京都府京都市",
    lat: 35.0167,
    lon: 135.7822,
    built: "",
    fact: "朱の社殿は平安京の朝堂院を再現している。",
    factSources: [{ title: "平安神宮公式：境内のご案内", url: "https://www.heianjingu.or.jp/map/guide/" }],
  },
  "mt-yotei": {
    officialName: "羊蹄山",
    place: "北海道（後志地方）",
    lat: 42.8267,
    lon: 140.8114,
    built: "",
    fact: "",
    factSources: [],
  },
  ouchijuku: {
    officialName: "大内宿",
    place: "福島県下郷町",
    lat: 37.3342,
    lon: 139.8608,
    built: "",
    fact: "会津と日光を結ぶ街道に、茅葺きの宿場町が残る。",
    factSources: [{ title: "大内宿観光協会公式", url: "https://www.ouchi-juku.com/" }],
  },
  kintaikyo: {
    officialName: "錦帯橋",
    place: "山口県岩国市",
    lat: 34.1676,
    lon: 132.1784,
    built: "1673年（今の橋体は2004年に架け替え）",
    fact: "五つの径間のうち、中央三つが木組みのアーチ。",
    factSources: [{ title: "岩国市：錦帯橋の構造", url: "https://kintaikyo.iwakuni-city.net/en/dimensions.html" }],
  },
  "arc-de-triomphe": {
    officialName: "エトワール凱旋門",
    place: "フランス・パリ",
    lat: 48.8738,
    lon: 2.295,
    built: "1836年",
    fact: "1806年に着工し、1836年に完成した。",
    factSources: [{ title: "凱旋門公式：History of the Arc de triomphe", url: "https://www.paris-arc-de-triomphe.fr/en/discover/histoire-de-l-arc-de-triomphe" }],
  },
  parthenon: {
    officialName: "パルテノン神殿",
    place: "ギリシャ・アテネ",
    lat: 37.9715,
    lon: 23.7266,
    built: "紀元前438年（紀元前447年着工）",
    fact: "女神アテーナーを祀る神殿。紀元前447年に着工し紀元前438年に完工。",
    factSources: [{ title: "ウィキペディア日本語版「パルテノン神殿」", url: "https://ja.wikipedia.org/wiki/%E3%83%91%E3%83%AB%E3%83%86%E3%83%8E%E3%83%B3%E7%A5%9E%E6%AE%BF" }],
  },
  "angkor-wat": {
    officialName: "アンコール・ワット",
    place: "カンボジア・シェムリアップ",
    lat: 13.4125,
    lon: 103.8667,
    built: "1113〜1150年",
    fact: "1113年から1150年に建てられた巨大な寺院。",
    factSources: [{ title: "APSARA National Authority：Angkor Wat", url: "https://apsaraauthority.gov.kh/2021/06/14/angkor-wat/" }],
  },
  "machu-picchu": {
    officialName: "マチュ・ピチュ",
    place: "ペルー・クスコ県",
    lat: -13.1633,
    lon: -72.5456,
    built: "15世紀",
    fact: "石の段畑と建物がアンデスの尾根に広がる。",
    factSources: [{ title: "UNESCO：Historic Sanctuary of Machu Picchu", url: "https://whc.unesco.org/en/list/274/" }],
  },
  "chichen-itza": {
    officialName: "チチェン・イッツァ",
    place: "メキシコ・ユカタン州",
    lat: 20.6831,
    lon: -88.5686,
    built: "",
    fact: "9段の基壇に4面の階段と頂上の神殿がある。",
    factSources: [{ title: "メキシコ国立人類学歴史研究所：Chichén Itzá", url: "https://lugares.inah.gob.mx/es/node/4335" }],
  },
  "abu-simbel": {
    officialName: "アブ・シンベル神殿",
    place: "エジプト・アスワン県",
    lat: 22.3369,
    lon: 31.6256,
    built: "紀元前1264年ごろ",
    fact: "正面の4体の巨像のうち1体は地震で崩れた。",
    factSources: [{ title: "エジプト観光・考古省：Abu Simbel", url: "https://egymonuments.gov.eg/archaeological-sites/abu-simbel/" }],
  },
  "tower-of-london": {
    officialName: "ロンドン塔",
    place: "イギリス・ロンドン",
    lat: 51.5081,
    lon: -0.0761,
    built: "",
    fact: "",
    factSources: [],
  },
  "westminster-abbey": {
    officialName: "ウェストミンスター寺院（聖ペテロ修道教会）",
    place: "イギリス・ロンドン",
    lat: 51.4994,
    lon: -0.1274,
    built: "",
    fact: "",
    factSources: [],
  },
  "notre-dame": {
    officialName: "パリのノートルダム大聖堂",
    place: "フランス・パリ",
    lat: 48.853,
    lon: 2.3498,
    built: "",
    fact: "",
    factSources: [],
  },
  "st-peters": {
    officialName: "サン・ピエトロ大聖堂",
    place: "バチカン市国",
    lat: 41.9022,
    lon: 12.4534,
    built: "",
    fact: "",
    factSources: [],
  },
  "brandenburg-gate": {
    officialName: "ブランデンブルク門",
    place: "ドイツ・ベルリン",
    lat: 52.5163,
    lon: 13.3777,
    built: "1791年",
    fact: "二列の六本柱が支え、上には四頭馬の戦車が立つ。",
    factSources: [{ title: "ベルリン観光局：Brandenburg Gate", url: "https://www.visitberlin.de/en/brandenburg-gate" }],
  },
  "forbidden-city": {
    officialName: "紫禁城（故宮）",
    place: "中国・北京",
    lat: 39.9158,
    lon: 116.3908,
    built: "",
    fact: "中央軸に宮殿が並び、太和殿が3層の白い基壇に立つ。",
    factSources: [{ title: "故宮博物院：Hall of Supreme Harmony", url: "https://intl.dpm.org.cn/hallsinfo/374.html" }],
  },
  "mont-saint-michel": {
    officialName: "モン・サン＝ミシェル",
    place: "フランス・ノルマンディー地方",
    lat: 48.6361,
    lon: -1.5114,
    built: "",
    fact: "海辺の岩山に修道院と城壁で囲まれた村が重なる。",
    factSources: [{ title: "モン・サン＝ミシェル観光局：The village and the ramparts", url: "https://www.ot-montsaintmichel.com/en/discover/visit-the-mont-saint-michel/visit-the-mont-saint-michel/the-village-and-the-ramparts/" }],
  },
  "mount-rushmore": {
    officialName: "ラシュモア山国立記念碑",
    place: "アメリカ・サウスダコタ州",
    lat: 43.8789,
    lon: -103.4592,
    built: "",
    fact: "",
    factSources: [],
  },
  "brooklyn-bridge": {
    officialName: "ブルックリン橋",
    place: "アメリカ・ニューヨーク",
    lat: 40.7057,
    lon: -73.9963,
    built: "1883年",
    fact: "1883年に完成した石造の主塔を持つ吊り橋。",
    factSources: [{ title: "ニューヨーク市交通局：Brooklyn Bridge", url: "https://www.nyc.gov/html/dot/html/infrastructure/brooklyn-bridge.shtml" }],
  },
  "mt-chokai": {
    officialName: "鳥海山",
    place: "秋田県・山形県",
    lat: 39.0989,
    lon: 140.0489,
    built: "",
    fact: "",
    factSources: [],
  },
  "mt-iwaki": {
    officialName: "岩木山",
    place: "青森県弘前市",
    lat: 40.6556,
    lon: 140.3031,
    built: "",
    fact: "",
    factSources: [],
  },
  "mt-kaimon": {
    officialName: "開聞岳",
    place: "鹿児島県指宿市",
    lat: 31.1803,
    lon: 130.5281,
    built: "",
    fact: "",
    factSources: [],
  },
  "mt-daisen": {
    officialName: "大山",
    place: "鳥取県大山町",
    lat: 35.3711,
    lon: 133.5461,
    built: "",
    fact: "",
    factSources: [],
  },
  gokayama: {
    officialName: "五箇山 相倉・菅沼合掌造り集落",
    place: "富山県南砺市",
    lat: 36.4285,
    lon: 136.9349,
    built: "",
    fact: "",
    factSources: [],
  },
  miyama: {
    officialName: "美山かやぶきの里（北村）",
    place: "京都府南丹市",
    lat: 35.3197,
    lon: 135.6197,
    built: "",
    fact: "京都の山里に39棟の茅葺き民家が残る。",
    factSources: [{ title: "美山かやぶきの里公式：里について", url: "https://kayabukinosato.jp/about/" }],
  },
  tsumagojuku: {
    officialName: "妻籠宿",
    place: "長野県南木曽町",
    lat: 35.5785,
    lon: 137.5953,
    built: "",
    fact: "中山道69次のうち、江戸から42番目の宿場。",
    factSources: [{ title: "妻籠宿公式：町並みの保存について", url: "https://tsumago.jp/learn/" }],
  },
  "tatsuoka-goryokaku": {
    officialName: "龍岡城五稜郭",
    place: "長野県佐久市",
    lat: 36.1897,
    lon: 138.4753,
    built: "",
    fact: "",
    factSources: [],
  },
  "christ-redeemer": {
    officialName: "コルコバードのキリスト像",
    place: "ブラジル・リオデジャネイロ",
    lat: -22.9519,
    lon: -43.2105,
    built: "",
    fact: "",
    factSources: [],
  },
  merlion: {
    officialName: "マーライオン像",
    place: "シンガポール",
    lat: 1.2868,
    lon: 103.8545,
    built: "",
    fact: "",
    factSources: [],
  },
  "humayun-tomb": {
    officialName: "フマーユーン廟",
    place: "インド・デリー",
    lat: 28.5933,
    lon: 77.2507,
    built: "1570年",
    fact: "赤砂岩の墓廟に白大理石のドームが載る。",
    factSources: [{ title: "UNESCO：Humayun’s Tomb, Delhi", url: "https://whc.unesco.org/en/list/232/" }],
  },
  "blue-mosque": {
    officialName: "スルタン・アフメト・モスク（ブルーモスク）",
    place: "トルコ・イスタンブール",
    lat: 41.0054,
    lon: 28.9768,
    built: "",
    fact: "連なるドームと6本のミナレットが特徴。",
    factSources: [{ title: "トルコ観光公式：Blue Mosque", url: "https://goturkiye.com/istanbul/blue-mosque" }],
  },
  "hadrians-wall": {
    officialName: "ハドリアヌスの長城",
    place: "イギリス・イングランド北部",
    lat: 55.0131,
    lon: -2.3302,
    built: "",
    fact: "壁沿いには門を持つ小砦が1マイルごとに設けられた。",
    factSources: [{ title: "English Heritage：Description of Hadrian’s Wall", url: "https://www.english-heritage.org.uk/visit/places/hadrians-wall/hadrians-wall-history-and-stories/history/description/" }],
  },
  "arena-verona": {
    officialName: "アレーナ・ディ・ヴェローナ",
    place: "イタリア・ヴェローナ",
    lat: 45.439,
    lon: 10.9944,
    built: "",
    fact: "",
    factSources: [],
  },
  "hohenzollern-castle": {
    officialName: "ホーエンツォレルン城",
    place: "ドイツ・ヘッヒンゲン",
    lat: 48.3233,
    lon: 8.9675,
    built: "",
    fact: "",
    factSources: [],
  },
}

export const LANDMARK_FACTS: Readonly<Record<string, LandmarkFacts>> = { ...LEGACY_FACTS, ...EXPANSION_FACTS }
