// 占い師が知っている料理の一覧。1行＝[id, 名前, よみ（検索用・空白区切りで別名も可）, 絵文字, 特徴]。
// 特徴は「質問id」または「質問id:確率」を空白で並べる。確率はその料理を思い浮かべた人が「はい」と答える見込み。
//   hot        → 1（はい）
//   spicy:.5   → 0.5（人によって答えが割れる）
//   hot:0      → 0（いいえ。質問の base が 0 より大きいときに、はっきり打ち消したい場合に書く）
// 書かれていない質問は questions.js の base を使う。値は筆者が日本の一般的な食卓を想定して付けた目安で、
// 統計ではない。外れた答え方は、遊んだ人の端末の中で学習して寄せていく（memory.js）。

const RAW = [
  // ご飯もの
  ['curry', 'カレーライス', 'かれーらいす カレー', '🍛', 'hot rice spoon curry simmered spicy:.5 japan:.5 western:.6 ethnic:.15 meat:.6 beef:.4 pork:.5 chicken:.3 veggie:.6 home:.95 conbini:.8 brown:.9 yellow:.3 heavy:.7 light:.1 winter:.5 summer:.5 toro:.5'],
  ['gyudon', '牛丼', 'ぎゅうどん', '🍚', 'hot rice bowl chopsticks meat beef soy amakara japan simmered brown:.8 conbini:.7 home:.3 heavy:.6 light:.2'],
  ['oyakodon', '親子丼', 'おやこどん', '🍚', 'hot rice bowl chopsticks spoon:.3 meat:.5 chicken egg soy amakara japan simmered home:.6 conbini:.5 light:.4 heavy:.3 yellow:.7 brown:.3 toro:.7'],
  ['katsudon', 'カツ丼', 'かつどん', '🍚', 'hot rice bowl chopsticks meat pork fried egg soy amakara japan simmered:.4 heavy:.9 light:0 brown:.8 yellow:.3 home:.3 conbini:.6 crispy:.3 toro:.4'],
  ['tendon', '天丼', 'てんどん', '🍤', 'hot rice bowl chopsticks fried shrimp:.9 seafood:.2 fish:.2 veggie:.3 soy amakara japan brown heavy:.6 light:.2 luxury:.25 home:.1 conbini:.3 crispy:.6'],
  ['kaisendon', '海鮮丼', 'かいせんどん', '🐟', 'rice bowl chopsticks fish shrimp:.5 seafood:.7 raw japan cold:.5 hot:0 luxury:.6 light:.7 heavy:.1 soy:.5 home:.15 conbini:.2 red:.4 local:.2 summer:.4 winter:.15 newyear:.2'],
  ['unaju', 'うな重', 'うなじゅう うなどん', '🍱', 'hot rice bowl:.8 chopsticks fish grilled soy amakara japan luxury brown summer:.6 home:.05 heavy:.5 light:.2 conbini:.2 toro:.5'],
  ['butadon', '豚丼', 'ぶたどん', '🍚', 'hot rice bowl chopsticks meat pork grilled soy amakara japan local:.5 brown home:.3 heavy:.6 conbini:.4'],
  ['chukadon', '中華丼', 'ちゅうかどん', '🍚', 'hot rice bowl spoon:.6 chopsticks:.6 chinese:.8 japan:.4 veggie shrimp:.5 seafood:.4 pork:.5 meat:.2 simmered:.5 white:.3 brown:.4 light:.5 home:.3 toro:.7'],
  ['omurice', 'オムライス', 'おむらいす', '🍳', 'hot rice spoon egg chicken:.5 tomato:.9 western japan:.8 grilled:.6 home:.8 conbini:.4 yellow:.9 red:.4 heavy:.5 light:.2 toro:.5'],
  ['chahan', 'チャーハン', 'ちゃーはん やきめし', '🍚', 'hot rice spoon:.8 chopsticks:.4 chinese egg:.6 pork:.5 grilled home:.8 conbini:.5 light:.3 heavy:.5 garlic:.3 brown:.4 yellow:.3'],
  ['bibimbap', 'ビビンバ', 'びびんば', '🍚', 'hot:.8 rice bowl:.4 spoon korean veggie egg:.7 beef:.5 meat:.4 spicy:.6 red:.4 home:.3 conbini:.3 light:.4 heavy:.3'],
  ['onigiri', 'おにぎり', 'おにぎり おむすび お握り', '🍙', 'rice hands japan conbini:1 home:.8 breakfast:.6 snack:.7 light:.8 heavy:.05 hot:.1 cold:.15 white:.7 round:.3 fish:.2 mochimochi:.3'],
  ['sushi', '寿司', 'すし にぎりずし お寿司 鮨 寿し', '🍣', 'rice raw fish shrimp:.5 seafood:.7 hands:.5 chopsticks:.8 japan luxury:.75 light:.7 heavy:.1 soy:.8 sour:.4 conbini:.3 home:.1 cold:.4 hot:0 red:.3 sake:.4 dip:.6 newyear:.3'],
  ['inari', 'いなり寿司', 'いなりずし おいなりさん', '🍣', 'rice hands:.6 chopsticks:.6 tofu japan amakara sour:.3 wrapped:.8 conbini:.7 home:.4 brown snack:.3 light:.5 cold:.2 hot:0 mochimochi:.2'],
  ['takikomi', '炊き込みご飯', 'たきこみごはん かやくごはん', '🍚', 'hot rice chopsticks japan soy home:.6 veggie:.4 chicken:.4 brown:.6 light:.6 heavy:.2 conbini:.4 winter:.3'],
  ['ochazuke', 'お茶漬け', 'おちゃづけ', '🍵', 'hot rice soup chopsticks japan light:.95 heavy:0 fish:.3 snack:.5 home:.7 breakfast:.3 sake:.1'],
  ['okayu', 'おかゆ・雑炊', 'おかゆ ぞうすい', '🍚', 'hot rice soup spoon japan light:.95 heavy:0 winter:.7 egg:.4 home:.6 white:.6 breakfast:.3 toro:.7'],
  ['hayashi', 'ハヤシライス', 'はやしらいす', '🍛', 'hot rice spoon meat:.6 beef simmered tomato:.5 japan:.7 western brown heavy:.6 light:.1 home:.5 conbini:.3 toro:.5'],
  ['locomoco', 'ロコモコ', 'ろこもこ', '🍚', 'hot rice bowl:.6 spoon:.7 meat beef egg western grilled heavy brown:.6 local:.5 home:.2 americas:.7'],
  ['tacorice', 'タコライス', 'たこらいす', '🍚', 'rice bowl:.4 spoon meat:.6 beef:.6 cheese:.6 tomato:.4 veggie:.5 spicy:.3 japan local:.9 hot:.4 cold:.1 heavy:.4 americas:.4'],
  ['gapao', 'ガパオライス', 'がぱおらいす', '🍚', 'hot rice spoon ethnic chicken meat:.6 egg:.8 spicy:.6 garlic:.4 grilled:.7 heavy:.4'],
  ['khaomangai', 'カオマンガイ', 'かおまんがい', '🍚', 'hot:.7 rice spoon:.6 chopsticks:.3 ethnic chicken meat:.6 simmered:.4 light:.5 white:.5 garlic:.3'],
  ['paella', 'パエリア', 'ぱえりあ', '🥘', 'hot rice spoon shrimp:.9 seafood:.8 fish:.3 chicken:.3 western luxury:.35 yellow:.7 red:.3 tomato:.2 grilled:.3'],
  ['risotto', 'リゾット', 'りぞっと', '🍚', 'hot rice spoon cheese:.7 cream:.6 western simmered white:.5 light:.3 heavy:.4 toro:.6'],
  ['doria', 'ドリア', 'どりあ', '🧀', 'hot rice spoon cheese cream western japan:.6 grilled:.6 white:.4 brown:.4 heavy:.6 winter:.6 home:.3 conbini:.4 toro:.6'],
  ['tenshinhan', '天津飯', 'てんしんはん かにたま', '🍳', 'hot rice spoon egg chinese:.8 japan:.5 seafood:.4 amakara:.4 sour:.2 yellow:.8 home:.2 toro:.8'],
  ['kimbap', 'キンパ', 'きんぱ', '🍙', 'rice chopsticks:.6 hands:.5 korean veggie egg:.6 beef:.3 wrapped:.7 conbini:.3 cold:.2 hot:.05 light:.5 round:.4 home:.3 mochimochi:.2'],
  ['tkg', '卵かけご飯', 'たまごかけごはん tkg 卵ご飯 たまごごはん', '🥚', 'rice egg chopsticks japan soy home:.95 breakfast:.8 light:.6 heavy:.1 hot:.6 snack:.4 yellow:.6 toro:.8'],
  ['natto', '納豆ごはん', 'なっとうごはん 納豆', '🍚', 'rice tofu chopsticks japan soy home:.95 breakfast:.8 light:.6 hot:.6 snack:.3 brown:.4 toro'],

  // 麺
  ['ramen', 'ラーメン', 'らーめん', '🍜', 'hot noodle soup chopsticks chinese:.5 japan:.6 pork:.7 meat:.3 egg:.3 soy:.5 miso:.3 heavy:.6 light:.2 garlic:.3 winter:.8 summer:.1 conbini:.4 home:.2 sake:.2 toro:.2'],
  ['tsukemen', 'つけ麺', 'つけめん', '🍜', 'noodle soup:.5 chopsticks japan heavy:.8 light:.1 pork:.5 fish:.3 hot:.5 cold:.3 soy:.5 brown:.5 dip mochimochi:.6 toro:.3'],
  ['udon', 'うどん', 'うどん 饂飩', '🍜', 'hot:.8 cold:.3 noodle soup:.8 chopsticks japan light:.8 heavy:.1 white:.8 home:.6 conbini:.6 soy:.7 local:.2 winter:.6 summer:.3 dip:.3 newyear:.1 mochimochi:.6'],
  ['soba', 'そば', 'そば ざるそば 蕎麦', '🍜', 'hot:.5 cold:.6 noodle soup:.6 chopsticks japan light:.9 heavy:.05 soy:.8 brown:.5 summer:.5 winter:.4 home:.3 conbini:.6 dip:.6 newyear'],
  ['yakisoba', '焼きそば', 'やきそば 焼そば', '🍜', 'hot noodle chopsticks japan:.8 chinese:.2 sauce:.7 grilled pork:.7 veggie:.6 festival:.9 home:.7 conbini:.6 brown heavy:.5 light:.2'],
  ['napolitan', 'ナポリタン', 'なぽりたん', '🍝', 'hot noodle fork tomato japan western grilled red:.8 pork:.3 veggie:.4 home:.6 conbini:.4 heavy:.4 light:.2'],
  ['carbonara', 'カルボナーラ', 'かるぼなーら', '🍝', 'hot noodle fork cream cheese egg:.7 pork:.7 western heavy:.8 light:.05 white:.5 yellow:.5 home:.4 conbini:.4 toro:.6'],
  ['meatsauce', 'ミートソース', 'みーとそーす ぼろねーぜ', '🍝', 'hot noodle fork tomato meat:.6 beef:.6 pork:.5 western simmered:.5 red:.6 brown:.4 cheese:.3 home:.6 conbini:.5 heavy:.5'],
  ['peperoncino', 'ペペロンチーノ', 'ぺぺろんちーの', '🍝', 'hot noodle fork garlic spicy:.6 western light:.5 heavy:.2 home:.5 conbini:.3'],
  ['tarakopasta', 'たらこスパゲッティ', 'たらこすぱげってぃ めんたいこぱすた', '🍝', 'hot noodle fork fish:.4 japan western:.7 cream:.3 home:.6 conbini:.5 light:.4 red:.3'],
  ['somen', 'そうめん', 'そうめん ひやむぎ 素麺', '🍜', 'cold noodle chopsticks japan summer:.95 winter:.05 light:.95 heavy:0 white soup:.5 soy:.6 home:.9 dip'],
  ['hiyashichuka', '冷やし中華', 'ひやしちゅうか', '🍜', 'cold noodle chopsticks japan chinese:.6 summer:.95 winter:0 light:.8 veggie:.7 egg:.5 pork:.3 sour:.7 soy:.5 conbini:.8 home:.5 yellow:.4'],
  ['tantanmen', '担々麺', 'たんたんめん', '🍜', 'hot noodle soup chopsticks chinese spicy pork:.5 meat:.3 red:.7 heavy:.7 garlic:.3 winter:.5'],
  ['champon', 'ちゃんぽん', 'ちゃんぽん', '🍜', 'hot noodle soup chopsticks japan local shrimp:.7 seafood:.8 pork veggie white:.7 heavy:.5 chinese:.3 toro:.2'],
  ['pho', 'フォー', 'ふぉー', '🍜', 'hot noodle soup chopsticks spoon:.4 ethnic chicken:.5 beef:.5 light:.8 white:.5 mochimochi:.3'],
  ['reimen', '冷麺', 'れいめん', '🍜', 'cold noodle soup chopsticks korean:.8 japan:.3 summer:.9 beef:.3 egg:.4 spicy:.3 sour:.4 local:.4 light:.7 mochimochi:.8'],
  ['mazesoba', 'まぜそば・油そば', 'まぜそば あぶらそば', '🍜', 'noodle chopsticks japan heavy:.9 light:0 garlic:.6 pork:.6 egg:.5 hot:.6 soy:.5 mochimochi:.6'],
  ['cupnoodle', 'カップラーメン', 'かっぷらーめん かっぷめん', '🍜', 'hot noodle soup chopsticks japan conbini snack:.7 home:.4 light:.2 heavy:.4 winter:.5'],

  // パン・粉もの・包むもの
  ['hamburger', 'ハンバーガー', 'はんばーがー', '🍔', 'bread hands meat beef grilled western cheese:.4 veggie:.3 tomato:.3 heavy:.8 light:.1 hot:.5 conbini:.3 home:.1 snack:.3 sandwiched americas'],
  ['sandwich', 'サンドイッチ', 'さんどいっち', '🥪', 'bread hands western egg:.5 veggie:.5 conbini home:.5 breakfast:.6 snack:.5 light:.7 heavy:.1 hot:.05 cold:.3 sandwiched bakery:.6'],
  ['pizza', 'ピザ', 'ぴざ', '🍕', 'hot bread:.5 hands cheese tomato western grilled heavy:.6 light:.1 red:.3 round sake:.4 home:.1 bakery:.1 mochimochi:.3 crispy:.4'],
  ['hotdog', 'ホットドッグ', 'ほっとどっぐ ふらんくふると', '🌭', 'hot:.7 bread hands meat:.5 pork:.6 western tomato:.4 festival:.4 conbini:.3 snack:.4 sandwiched americas bakery:.3'],
  ['okonomiyaki', 'お好み焼き', 'おこのみやき お好み焼', '🥞', 'hot konamon grilled sauce japan local:.6 pork:.7 veggie:.7 egg:.4 shrimp:.3 seafood:.3 festival:.6 home:.5 chopsticks:.5 round brown heavy:.6 mochimochi:.3 crispy:.2'],
  ['takoyaki', 'たこ焼き', 'たこやき たこ焼', '🐙', 'hot konamon grilled seafood sauce japan local:.6 festival:.95 round snack:.8 brown:.7 chopsticks:.3 hands:.3 conbini:.3 home:.3 sake:.4 mochimochi:.3 crispy:.4 toro:.5'],
  ['monja', 'もんじゃ焼き', 'もんじゃやき', '🥘', 'hot konamon grilled japan local shrimp:.3 seafood:.3 veggie:.6 sauce:.4 sake:.4 brown:.5 toro:.8'],
  ['gyoza', '餃子', 'ぎょうざ ぎょーざ 焼き餃子', '🥟', 'hot wrapped pork veggie:.5 garlic:.7 chinese:.8 japan:.3 grilled chopsticks okazu:.8 home:.5 conbini:.5 local:.2 sake:.6 brown:.4 dip:.8 mochimochi:.3 crispy:.5'],
  ['nikuman', '肉まん', 'にくまん ぶたまん', '🥟', 'hot wrapped pork meat:.5 hands chinese:.7 conbini winter white round snack:.8 dip:.2 mochimochi:.6'],
  ['xiaolongbao', '小籠包', 'しょうろんぽう', '🥟', 'hot wrapped pork soup:.4 chinese spoon:.4 chopsticks round luxury:.3 white:.5 dip:.5 mochimochi:.4 toro:.5'],
  ['toast', 'トースト', 'とーすと しょくぱん', '🍞', 'hot:.6 bread breakfast:.95 home:.9 grilled light:.5 brown:.4 snack:.3 hands western:.5 bakery:.5 crispy:.8'],
  ['frenchtoast', 'フレンチトースト', 'ふれんちとーすと', '🍞', 'hot bread egg cream sweet:.7 breakfast:.6 home:.5 western:.6 fork yellow:.5 bakery:.2'],
  ['pancake', 'パンケーキ', 'ぱんけーき ほっとけーき', '🥞', 'hot sweet cream:.4 egg:.4 breakfast:.4 western:.6 fork home:.5 round fruit:.4 brown:.3 americas:.5 mochimochi:.2'],
  ['croissant', 'クロワッサン', 'くろわっさん', '🥐', 'bread hands breakfast:.7 western conbini:.4 hot:.2 light:.3 heavy:.3 brown:.4 sandwiched:.2 bakery crispy:.9'],
  ['currypan', 'カレーパン', 'かれーぱん', '🥐', 'bread fried curry hands japan conbini snack:.8 brown heavy:.5 spicy:.3 hot:.4 bakery crispy:.8'],
  ['melonpan', 'メロンパン', 'めろんぱん', '🍞', 'bread sweet hands japan conbini snack:.8 round yellow:.6 bakery mochimochi:.2 crispy:.6'],
  ['bagel', 'ベーグル', 'べーぐる', '🥯', 'bread hands round western light:.5 breakfast:.5 conbini:.3 sandwiched:.3 americas:.5 bakery:.9 mochimochi:.9'],
  ['tacos', 'タコス', 'たこす', '🌮', 'hands meat:.6 beef:.5 veggie:.5 spicy:.5 cheese:.4 tomato:.4 wrapped:.5 western:.3 ethnic:.2 hot:.4 sandwiched:.6 americas'],
  ['kebab', 'ケバブ', 'けばぶ', '🥙', 'hot hands bread:.6 meat beef:.4 chicken:.5 grilled festival:.5 spicy:.3 ethnic:.3 wrapped:.4 heavy:.5 sandwiched:.7'],
  ['harumaki', '春巻き', 'はるまき', '🥢', 'hot fried wrapped chinese pork:.6 veggie:.6 chopsticks okazu:.7 home:.3 conbini:.4 brown:.5 dip:.3 crispy:.9'],
  ['namaharumaki', '生春巻き', 'なまはるまき', '🥬', 'cold:.6 wrapped ethnic shrimp:.8 veggie light:.9 hands:.5 chopsticks:.5 white:.5 dip:.7'],

  // 肉
  ['yakiniku', '焼肉', 'やきにく', '🥩', 'hot grilled meat beef pork:.5 chopsticks korean:.4 japan:.5 luxury:.6 heavy:.8 light:.1 okazu:.6 garlic:.5 amakara:.6 soy:.4 brown sake:.6 dip:.6'],
  ['steak', 'ステーキ', 'すてーき', '🥩', 'hot grilled meat beef fork western luxury:.8 heavy:.8 brown garlic:.4 okazu:.3 americas:.3'],
  ['hamburg', 'ハンバーグ', 'はんばーぐ', '🍖', 'hot grilled meat beef pork:.6 fork western japan:.5 home:.8 okazu brown heavy:.5 sauce:.4 tomato:.3 conbini:.3 round:.4'],
  ['karaage', 'からあげ', 'からあげ とりのからあげ 唐揚げ から揚げ', '🍗', 'hot:.7 fried chicken meat chopsticks:.6 hands:.3 japan okazu home:.7 conbini:.9 festival:.4 brown heavy:.6 garlic:.4 soy:.5 snack:.4 sake:.7 crispy:.7'],
  ['tonkatsu', 'とんかつ', 'とんかつ 豚カツ', '🍖', 'hot fried pork meat chopsticks japan western:.4 sauce okazu brown heavy:.8 home:.4 conbini:.4 dip:.3 crispy:.9'],
  ['shogayaki', '生姜焼き', 'しょうがやき', '🍖', 'hot grilled pork meat chopsticks japan soy amakara okazu home:.8 brown conbini:.3'],
  ['yakitori', '焼き鳥', 'やきとり 焼鳥', '🍢', 'hot grilled chicken meat skewer hands:.8 japan soy:.5 amakara:.5 festival:.5 conbini:.5 brown sake:.95 snack:.3 crispy:.2'],
  ['sukiyaki', 'すき焼き', 'すきやき', '🍲', 'hot simmered pot beef meat egg:.6 chopsticks japan soy amakara luxury:.8 winter:.8 veggie:.4 tofu:.6 brown:.5 dip:.6 newyear:.3 toro:.3'],
  ['shabushabu', 'しゃぶしゃぶ', 'しゃぶしゃぶ', '🍲', 'hot pot soup beef:.7 pork:.6 meat chopsticks japan luxury:.7 light:.6 veggie:.6 winter:.7 dip'],
  ['motsunabe', 'もつ鍋', 'もつなべ', '🍲', 'hot pot soup meat beef:.6 japan local garlic:.6 veggie:.7 miso:.4 soy:.5 winter:.8 heavy:.5 sake:.6'],
  ['roastbeef', 'ローストビーフ', 'ろーすとびーふ', '🥩', 'beef meat western luxury:.7 fork cold:.4 hot:.2 red:.6 bowl:.2 light:.4 sake:.4'],
  ['friedchicken', 'フライドチキン', 'ふらいどちきん', '🍗', 'hot fried chicken meat hands western heavy:.8 conbini:.5 brown winter:.3 snack:.3 americas:.8 crispy:.8'],
  ['subuta', '酢豚', 'すぶた', '🥢', 'hot fried pork meat chinese amakara sour veggie:.6 okazu chopsticks red:.3 brown:.4 crispy:.4'],
  ['hoikoro', '回鍋肉', 'ほいこーろー', '🥬', 'hot grilled pork meat chinese miso veggie spicy:.4 amakara:.5 okazu chopsticks home:.4'],
  ['chinjao', '青椒肉絲', 'ちんじゃおろーす', '🫑', 'hot grilled meat pork:.5 beef:.5 chinese veggie okazu chopsticks soy:.4 home:.4'],
  ['chickennanban', 'チキン南蛮', 'ちきんなんばん', '🍗', 'hot fried chicken meat japan local sour:.6 amakara:.5 okazu heavy:.7 chopsticks conbini:.4 crispy:.5'],
  ['kakuni', '角煮', 'かくに ぶたのかくに', '🍖', 'hot simmered pork meat japan:.5 chinese:.4 soy amakara brown chopsticks okazu heavy luxury:.3 local:.3 toro:.8'],
  ['samgyeopsal', 'サムギョプサル', 'さむぎょぷさる', '🥓', 'hot grilled pork meat korean veggie:.6 garlic:.6 hands:.4 chopsticks heavy:.6 sake:.5 dip:.6 crispy:.5'],
  ['jingisukan', 'ジンギスカン', 'じんぎすかん', '🍖', 'hot grilled meat japan local:.95 veggie:.6 soy:.4 amakara:.4 chopsticks sake:.5 heavy:.5 dip:.3'],
  ['nikujaga', '肉じゃが', 'にくじゃが', '🥔', 'hot simmered meat:.4 beef:.6 pork:.5 japan soy amakara home:.9 okazu veggie chopsticks brown light:.4'],
  ['rollcabbage', 'ロールキャベツ', 'ろーるきゃべつ', '🥬', 'hot simmered wrapped veggie meat:.5 pork:.5 beef:.4 western tomato:.4 soup:.5 home:.5 light:.5'],
  ['creamstew', 'クリームシチュー', 'くりーむしちゅー しちゅー', '🥣', 'hot simmered cream soup spoon veggie chicken:.6 japan:.6 western white winter:.9 home:.8 toro:.6'],
  ['beefstew', 'ビーフシチュー', 'びーふしちゅー', '🥣', 'hot simmered beef meat tomato:.4 spoon western brown luxury:.4 winter:.8 heavy:.7 soup:.5 toro:.5'],
  ['gratin', 'グラタン', 'ぐらたん まかろにぐらたん', '🧀', 'hot cheese cream grilled western spoon:.7 fork:.4 white:.4 brown:.4 winter:.7 noodle:.2 shrimp:.5 chicken:.3 home:.4 conbini:.4 heavy:.5 toro:.6'],
  ['korokke', 'コロッケ', 'ころっけ', '🥔', 'hot:.7 fried japan western:.5 veggie:.6 beef:.3 meat:.2 sauce okazu chopsticks:.6 hands:.3 conbini:.7 brown snack:.4 home:.4 round:.5 crispy:.9'],
  ['menchi', 'メンチカツ', 'めんちかつ', '🍖', 'hot fried meat beef pork:.6 sauce japan western:.4 okazu brown heavy:.8 round:.4 crispy:.9'],
  ['ebifry', 'エビフライ', 'えびふらい 海老フライ', '🍤', 'hot fried shrimp japan western:.5 okazu sauce:.6 brown sour:.2 dip:.3 crispy:.9'],
  ['tempura', '天ぷら', 'てんぷら 天麩羅', '🍤', 'hot fried shrimp:.9 seafood:.3 veggie:.6 fish:.3 japan chopsticks luxury:.4 light:.3 soy:.4 brown:.4 yellow:.4 sake:.4 dip:.5 crispy:.8'],
  ['kushikatsu', '串カツ', 'くしかつ くしあげ', '🍢', 'hot fried skewer meat:.5 pork:.5 veggie:.4 shrimp:.3 sauce japan local hands sake:.8 brown dip crispy:.9'],
  ['gyutan', '牛タン', 'ぎゅうたん', '🥩', 'hot grilled beef meat japan local luxury:.5 chopsticks okazu light:.4 sake:.6 dip:.2'],

  // 魚
  ['sashimi', '刺身', 'さしみ おさしみ お刺身', '🐟', 'raw fish shrimp:.3 seafood:.6 japan chopsticks soy luxury:.5 light:.9 heavy:0 red:.4 cold:.6 hot:0 okazu:.5 sake:.8 dip:.8'],
  ['yakizakana', '焼き魚', 'やきざかな しおやき 焼魚', '🐟', 'hot grilled fish japan chopsticks okazu home:.7 breakfast:.5 light:.8 heavy:.05 brown:.3 soy:.3 conbini:.3'],
  ['sabamiso', 'さばの味噌煮', 'さばのみそに', '🐟', 'hot simmered fish miso japan okazu home:.6 chopsticks brown amakara:.5 conbini:.3 toro:.2'],
  ['kakifry', 'カキフライ', 'かきふらい 牡蠣フライ', '🦪', 'hot fried seafood japan western:.4 sauce:.6 okazu winter:.8 brown dip:.3 crispy:.9'],
  ['ebichili', 'エビチリ', 'えびちり 海老チリ', '🦐', 'hot shrimp chinese spicy:.6 red tomato:.5 amakara:.5 okazu chopsticks home:.3'],

  // 鍋・汁もの
  ['oden', 'おでん', 'おでん', '🍢', 'hot simmered pot:.3 soup japan egg:.5 fish:.4 tofu:.4 veggie:.4 winter:.95 summer:0 conbini:.9 light:.7 skewer:.3 chopsticks brown:.4 sake:.6 newyear:.2 toro:.3'],
  ['yosenabe', '寄せ鍋', 'よせなべ なべ', '🍲', 'hot pot soup simmered japan fish:.5 shrimp:.5 seafood:.5 chicken:.5 veggie tofu:.6 winter:.9 light:.7 soy:.5 chopsticks home:.6 dip:.3 newyear:.3'],
  ['kimchinabe', 'キムチ鍋', 'きむちなべ', '🍲', 'hot pot soup korean:.7 japan:.3 spicy red pork:.6 veggie tofu:.6 winter:.9 garlic:.4 heavy:.4 home:.6'],
  ['misoshiru', '味噌汁', 'みそしる おみそしる みそ汁', '🥣', 'hot soup miso japan tofu:.6 veggie:.5 home:.95 breakfast:.8 light:.9 heavy:0 chopsticks okazu:.2 brown:.4'],
  ['tonjiru', '豚汁', 'とんじる ぶたじる とん汁', '🥣', 'hot soup miso pork veggie japan home:.8 winter:.8 chopsticks light:.4 heavy:.3 brown:.4'],
  ['sundubu', 'スンドゥブ', 'すんどぅぶ', '🍲', 'hot soup korean spicy red tofu shrimp:.4 seafood:.5 egg:.5 spoon winter:.8 toro:.6'],
  ['tomyum', 'トムヤムクン', 'とむやむくん', '🍲', 'hot soup ethnic spicy sour shrimp seafood:.3 red:.5 spoon light:.5'],
  ['kiritanpo', 'きりたんぽ鍋', 'きりたんぽなべ きりたんぽ', '🍲', 'hot pot soup rice:.7 japan local chicken veggie soy winter:.95 chopsticks light:.5 skewer:.2 newyear:.2 mochimochi:.7'],

  // 中華・韓国・エスニック
  ['mapotofu', '麻婆豆腐', 'まーぼーどうふ', '🌶️', 'hot tofu chinese spicy red meat:.3 pork:.5 spoon:.5 chopsticks:.6 okazu home:.5 simmered:.4 garlic:.3 conbini:.3 toro:.7'],
  ['chijimi', 'チヂミ', 'ちぢみ ちじみ', '🥞', 'hot grilled konamon:.6 korean veggie shrimp:.3 seafood:.5 chopsticks round:.5 sake:.5 dip:.7 mochimochi:.6 crispy:.6'],
  ['tteokbokki', 'トッポッキ', 'とっぽっき とっぽぎ', '🌶️', 'hot korean spicy red amakara rice:.5 simmered chopsticks snack:.5 festival:.2 mochimochi'],
  ['greencurry', 'グリーンカレー', 'ぐりーんかれー', '🍛', 'hot rice:.7 spoon curry:.8 ethnic spicy chicken:.6 cream:.3 soup:.5'],
  ['indiancurry', 'インドカレーとナン', 'いんどかれー なん', '🍛', 'hot curry spicy ethnic bread:.5 hands:.6 chicken:.5 cream:.3 spoon:.3 brown:.5 yellow:.4 mochimochi:.4'],

  // 卵・副菜・軽いもの
  ['chawanmushi', '茶碗蒸し', 'ちゃわんむし', '🥚', 'hot egg japan spoon light shrimp:.6 seafood:.2 chicken:.3 luxury:.2 yellow:.6 toro:.8'],
  ['dashimaki', 'だし巻き卵', 'だしまきたまご たまごやき', '🍳', 'egg japan chopsticks okazu home:.7 light:.7 breakfast:.4 hot:.5 yellow sake:.4 toro:.4'],
  ['salad', 'サラダ', 'さらだ', '🥗', 'cold:.6 veggie light:.95 heavy:0 western:.5 fork:.4 chopsticks:.4 home:.7 conbini:.8 hot:0 crispy:.3'],
  ['fries', 'フライドポテト', 'ふらいどぽてと ぽてと', '🍟', 'hot fried hands veggie:.2 western snack:.8 festival:.4 conbini:.5 heavy:.4 light:.1 sake:.6 yellow:.6 dip:.3 americas:.6 crispy:.7'],
  ['yakiimo', '焼きいも', 'やきいも 焼き芋 焼芋 石焼きいも', '🍠', 'hot grilled sweet:.6 hands japan winter:.95 snack:.8 conbini:.4 veggie:.3 mochimochi:.3'],
  ['potatochips', 'ポテトチップス', 'ぽてとちっぷす', '🥔', 'snack hands fried conbini light:.2 heavy:.3 hot:0 sake:.5 yellow:.5 crispy'],
  ['hiyayakko', '冷奴', 'ひややっこ', '🧊', 'cold tofu japan light:.95 heavy:0 soy summer:.9 chopsticks white okazu:.4 sake:.6 home:.6 toro:.4'],
  ['edamame', '枝豆', 'えだまめ', '🫛', 'tofu:.6 veggie:.5 hands japan sake:.95 summer:.9 light:.8 home:.4 snack:.4 cold:.3 hot:.3'],

  // あまいもの
  ['shortcake', 'ショートケーキ', 'しょーとけーき けーき', '🍰', 'sweet cream fruit cold:.5 western:.6 japan:.5 white fork:.6 luxury:.3 conbini:.6 sandwiched:.4'],
  ['cheesecake', 'チーズケーキ', 'ちーずけーき', '🍰', 'sweet cheese cream cold:.5 western:.6 conbini:.6 fork:.6 yellow:.4 white:.3 americas:.3'],
  ['pudding', 'プリン', 'ぷりん', '🍮', 'sweet cold egg cream spoon conbini japan:.4 western:.5 yellow brown:.4 home:.2 toro:.8'],
  ['icecream', 'アイスクリーム', 'あいすくりーむ あいす', '🍨', 'sweet cold cream spoon conbini summer:.95 white:.4 snack:.4 toro:.3'],
  ['softcream', 'ソフトクリーム', 'そふとくりーむ', '🍦', 'sweet cold cream hands summer:.9 white:.6 local:.1 snack:.4 toro:.4'],
  ['kakigori', 'かき氷', 'かきごおり', '🍧', 'sweet cold spoon summer festival:.8 fruit:.3 red:.4 japan light:.8 heavy:0'],
  ['parfait', 'パフェ', 'ぱふぇ', '🍨', 'sweet cold cream fruit chocolate:.4 spoon western:.5 japan:.4 luxury:.3'],
  ['donut', 'ドーナツ', 'どーなつ', '🍩', 'sweet fried hands round conbini snack:.8 western:.6 chocolate:.3 brown:.4 americas:.5 bakery:.4 mochimochi:.4 crispy:.3'],
  ['choux', 'シュークリーム', 'しゅーくりーむ', '🥐', 'sweet cream hands wrapped:.6 round:.5 conbini western:.6 yellow:.4 sandwiched:.3 bakery:.3 crispy:.3'],
  ['taiyaki', 'たい焼き', 'たいやき 鯛焼き', '🐟', 'sweet hot anko grilled hands japan festival:.4 snack:.8 winter:.5 brown mochimochi:.4 crispy:.3'],
  ['daifuku', '大福', 'だいふく いちごだいふく', '🍡', 'sweet anko rice:.4 hands japan wrapped round white conbini:.5 snack:.6 newyear:.3 mochimochi'],
  ['dango', 'だんご', 'だんご みたらしだんご 団子', '🍡', 'sweet rice:.4 skewer anko:.5 amakara:.5 hands japan conbini:.6 snack:.7 round newyear:.1 mochimochi'],
  ['dorayaki', 'どら焼き', 'どらやき どら焼', '🥞', 'sweet anko hands japan round brown conbini:.5 snack:.8 sandwiched:.9 mochimochi:.4'],
  ['crepe', 'クレープ', 'くれーぷ', '🌯', 'sweet wrapped cream fruit chocolate:.5 hands festival:.5 western:.6 cold:.3 sandwiched:.4 mochimochi:.3'],
  ['waffle', 'ワッフル', 'わっふる', '🧇', 'sweet hands:.6 western:.6 grilled cream:.3 snack:.6 brown:.4 mochimochi:.3 crispy:.5'],
  ['chocolate', 'チョコレート', 'ちょこれーと ちょこ', '🍫', 'sweet chocolate hands snack conbini brown hot:0 winter:.4 light:.2 heavy:.3 home:.05 luxury:.2'],
  ['cookie', 'クッキー', 'くっきー びすけっと', '🍪', 'sweet hands snack conbini round brown western:.6 grilled:.4 home:.3 crispy:.8'],
  ['anmitsu', 'あんみつ', 'あんみつ みつまめ', '🍧', 'sweet cold anko fruit spoon japan light:.6 summer:.6 mochimochi:.3 conbini:.4 home:.1 white:.3'],
  ['warabimochi', 'わらび餅', 'わらびもち', '🍡', 'sweet cold japan chopsticks:.3 hands:.3 light:.7 summer:.7 festival:.3 brown:.3 mochimochi:.8 toro:.5'],
  ['tiramisu', 'ティラミス', 'てぃらみす', '🍰', 'sweet cold cream cheese chocolate:.5 western:.6 spoon conbini:.5 brown:.5'],
  ['montblanc', 'モンブラン', 'もんぶらん', '🌰', 'sweet cream western:.6 brown:.6 fork:.5 conbini:.5 winter:.2 luxury:.2'],
  ['applepie', 'アップルパイ', 'あっぷるぱい', '🥧', 'sweet fruit grilled western:.6 hot:.4 brown wrapped:.4 americas:.4 bakery:.5 crispy:.7'],
  ['oshiruko', 'おしるこ・ぜんざい', 'おしるこ ぜんざい', '🥣', 'sweet hot anko soup rice:.4 japan winter:.95 chopsticks:.5 spoon:.4 newyear:.5 mochimochi:.8 toro:.5'],
  ['annin', '杏仁豆腐', 'あんにんどうふ', '🍮', 'sweet cold chinese spoon white fruit:.4 light:.8 conbini:.5 toro:.4'],
  ['senbei', 'せんべい', 'せんべい おせんべい 煎餅', '🍘', 'rice:.5 snack hands japan soy round brown conbini hot:0 sweet:.1 crispy'],
  ['wataame', 'わたあめ', 'わたあめ わたがし', '☁️', 'sweet festival:.95 hands white light:.6 japan:.2 snack:.4 summer:.7 skewer:.6 conbini:.05 home:0 hot:0'],
  ['chocobanana', 'チョコバナナ', 'ちょこばなな', '🍌', 'sweet festival:.95 chocolate fruit skewer hands cold:.2 japan:.4'],
  ['ringoame', 'りんご飴', 'りんごあめ', '🍎', 'sweet festival:.95 fruit hands red round skewer:.5 japan:.3'],
  ['ikayaki', 'いか焼き', 'いかやき', '🦑', 'hot grilled seafood festival:.8 soy:.5 amakara:.5 skewer:.5 japan hands sake:.6 brown'],
];

export const DISHES = Object.freeze(RAW.map(([id, name, kana, emoji, tags]) => Object.freeze({ id, name, kana, emoji, tags })));
