// 占い師が投げる質問の一覧。画面では頭に「それは、」を付けて出すので、text はその続きだけを書く。
// base は、料理データに値が書かれていないときの「はい」と答える確率。
// 材料や作り方のように事実で決まる質問は 0（書き漏れ＝いいえ）、
// 気分や印象で答えが割れる質問は少し上げて、書き漏れが強い「いいえ」にならないようにしている。
// katakana だけは料理名から自動で決める（dishes.js 側には書かない）。
// late: true の質問（名前・色・形・地方）は序盤に出さない。まだ料理を決めていない人には答えにくく、
// 最初に「名前がカタカナですか？」と聞かれると占いの雰囲気も崩れるため。

export const QUESTIONS = Object.freeze([
  { id: 'hot', text: '温かい料理ですか？', base: 0 },
  { id: 'cold', text: '冷たい、または冷やして食べるものですか？', base: 0 },
  { id: 'sweet', text: '甘いおやつやデザートですか？', base: 0 },
  { id: 'rice', text: 'ご飯やお米を使いますか？', base: 0 },
  { id: 'noodle', text: '麺類ですか？', base: 0 },
  { id: 'bread', text: 'パンの仲間ですか？', base: 0 },
  { id: 'konamon', text: 'お好み焼きやたこ焼きのような「粉もの」ですか？', base: 0 },
  { id: 'meat', text: 'お肉が主役ですか？', base: 0 },
  { id: 'beef', text: '牛肉を使いますか？', base: 0 },
  { id: 'pork', text: '豚肉を使いますか？', base: 0 },
  { id: 'chicken', text: '鶏肉を使いますか？', base: 0 },
  { id: 'fish', text: '魚が主役ですか？', base: 0 },
  { id: 'shrimp', text: 'エビを使いますか？', base: 0 },
  { id: 'seafood', text: 'イカ・タコ・貝・カニのどれかを使いますか？', base: 0 },
  { id: 'egg', text: '卵が目立つ料理ですか？', base: 0 },
  { id: 'raw', text: '生の魚や貝を使いますか？', base: 0 },
  { id: 'fried', text: '揚げ物ですか？', base: 0 },
  { id: 'grilled', text: '焼いたり炒めたりして作りますか？', base: 0 },
  { id: 'simmered', text: '煮込んで作りますか？', base: 0 },
  { id: 'soup', text: 'スープや汁に浸かっていますか？', base: 0 },
  { id: 'pot', text: '鍋を囲んで、みんなでつつくものですか？', base: 0 },
  { id: 'bowl', text: 'ご飯の上に具がのった丼ものですか？', base: 0 },
  { id: 'dip', text: 'つゆやタレにつけて食べますか？', base: 0 },
  { id: 'sandwiched', text: '具をはさんでいますか？', base: 0 },
  { id: 'spicy', text: '辛いですか？', base: 0 },
  { id: 'cheese', text: 'チーズを使いますか？', base: 0 },
  { id: 'tomato', text: 'トマトやケチャップの味がしますか？', base: 0 },
  { id: 'cream', text: '牛乳や生クリームを使いますか？', base: 0 },
  { id: 'curry', text: 'カレー味ですか？', base: 0 },
  { id: 'soy', text: 'しょうゆ味ですか？', base: 0.05 },
  { id: 'miso', text: 'みそ味ですか？', base: 0 },
  { id: 'sauce', text: 'とんかつソースやお好みソースをかけますか？', base: 0 },
  { id: 'amakara', text: '甘辛い味ですか？', base: 0 },
  { id: 'sour', text: '酸っぱい味がしますか？', base: 0 },
  { id: 'japan', text: '日本で生まれた料理ですか？', base: 0 },
  { id: 'chinese', text: '中華料理ですか？', base: 0 },
  { id: 'korean', text: '韓国料理ですか？', base: 0 },
  { id: 'western', text: '洋食ですか？', base: 0 },
  { id: 'ethnic', text: 'タイ・ベトナム・インドなど、アジアのエスニック料理ですか？', base: 0 },
  { id: 'americas', text: 'アメリカやメキシコの料理ですか？', base: 0 },
  { id: 'hands', text: '手で持って食べますか？', base: 0 },
  { id: 'spoon', text: 'スプーンで食べますか？', base: 0 },
  { id: 'chopsticks', text: 'はしで食べますか？', base: 0 },
  { id: 'fork', text: 'フォークやナイフで食べますか？', base: 0 },
  { id: 'home', text: '家でよく作りますか？', base: 0.3 },
  { id: 'conbini', text: 'コンビニで買えますか？', base: 0.2 },
  { id: 'festival', text: 'お祭りの屋台で見かけますか？', base: 0.02 },
  { id: 'bakery', text: 'パン屋さんで買いますか？', base: 0 },
  { id: 'newyear', text: '年越しやお正月に食べますか？', base: 0.02 },
  { id: 'luxury', text: 'ちょっとしたごちそう（お値段高め）ですか？', base: 0.05 },
  { id: 'summer', text: '暑い日に食べたくなりますか？', base: 0.2 },
  { id: 'winter', text: '寒い日に食べたくなりますか？', base: 0.25 },
  { id: 'breakfast', text: '朝ごはんに食べますか？', base: 0.05 },
  { id: 'okazu', text: 'ご飯のおかずになりますか？', base: 0.05 },
  { id: 'sake', text: 'お酒のおつまみになりますか？', base: 0.1 },
  { id: 'snack', text: '小腹がすいたときに食べますか？', base: 0.1 },
  { id: 'brown', text: '茶色っぽい見た目ですか？', base: 0.15, late: true },
  { id: 'red', text: '赤っぽい見た目ですか？', base: 0.03, late: true },
  { id: 'white', text: '白っぽい見た目ですか？', base: 0.08, late: true },
  { id: 'yellow', text: '黄色っぽい見た目ですか？', base: 0.05, late: true },
  { id: 'katakana', text: '名前がカタカナですか？', base: 0, late: true },
  { id: 'anko', text: 'あんこを使いますか？', base: 0 },
  { id: 'chocolate', text: 'チョコレートを使いますか？', base: 0 },
  { id: 'fruit', text: '果物を使いますか？', base: 0 },
  { id: 'skewer', text: '串に刺さっていますか？', base: 0 },
  { id: 'wrapped', text: '皮や生地で具を包んでいますか？', base: 0 },
  { id: 'round', text: '丸い形をしていますか？', base: 0.05, late: true },
  { id: 'veggie', text: '野菜がたっぷり入っていますか？', base: 0.1 },
  { id: 'tofu', text: '豆腐や大豆（納豆など）を使いますか？', base: 0 },
  { id: 'garlic', text: 'にんにくが効いていますか？', base: 0.05 },
  { id: 'mochimochi', text: 'もちもちした食感ですか？', base: 0.05 },
  { id: 'crispy', text: 'サクサク、パリパリした食感ですか？', base: 0.05 },
  { id: 'toro', text: 'とろとろ、ねばねばした食感ですか？', base: 0.05 },
  { id: 'light', text: 'あっさり、さっぱりしていますか？', base: 0.3 },
  { id: 'heavy', text: 'こってりしていて、食べごたえがありますか？', base: 0.3 },
  { id: 'local', text: 'どこかの地方の名物ですか？', base: 0.03, late: true },
]);

export const QUESTION_BY_ID = new Map(QUESTIONS.map(question => [question.id, question]));
