export const MAX_LEVEL = 30;
const UPGRADES = [
  { cooldown: 0.25, volleys: 2, columns: 1, width: 4, label: '' },
  { cooldown: 0.22, volleys: 2, columns: 1, width: 4, label: '連射が速くなった' },
  { cooldown: 0.22, volleys: 3, columns: 1, width: 4, label: '同時弾 3発' },
  { cooldown: 0.22, volleys: 3, columns: 1, width: 6, label: '弾が太くなった' },
  { cooldown: 0.20, volleys: 3, columns: 1, width: 6, label: '連射が速くなった' },
  { cooldown: 0.20, volleys: 3, columns: 2, width: 6, label: 'ツインショット' },
  { cooldown: 0.20, volleys: 4, columns: 2, width: 6, label: '同時弾 4発' },
  { cooldown: 0.20, volleys: 4, columns: 2, width: 8, label: '弾が太くなった' },
  { cooldown: 0.18, volleys: 4, columns: 2, width: 8, label: '連射が速くなった' },
  { cooldown: 0.18, volleys: 5, columns: 2, width: 8, label: '同時弾 5発' },
  { cooldown: 0.18, volleys: 5, columns: 2, width: 10, label: '弾が太くなった' },
  { cooldown: 0.16, volleys: 5, columns: 2, width: 10, label: '連射が速くなった' },
  { cooldown: 0.16, volleys: 5, columns: 3, width: 10, label: 'トリプルショット' },
  { cooldown: 0.16, volleys: 6, columns: 3, width: 10, label: '同時弾 6発' },
  { cooldown: 0.16, volleys: 6, columns: 3, width: 12, label: '弾が太くなった' },
  { cooldown: 0.15, volleys: 6, columns: 3, width: 12, label: '連射が速くなった' },
  { cooldown: 0.15, volleys: 7, columns: 3, width: 12, label: '同時弾 7発' },
  { cooldown: 0.15, volleys: 7, columns: 3, width: 13, label: '弾が太くなった' },
  { cooldown: 0.14, volleys: 7, columns: 3, width: 13, label: '連射が速くなった' },
  { cooldown: 0.14, volleys: 8, columns: 3, width: 13, label: '同時弾 8発' },
  { cooldown: 0.14, volleys: 8, columns: 3, width: 14, label: '弾が太くなった' },
  { cooldown: 0.13, volleys: 8, columns: 3, width: 14, label: '連射が速くなった' },
  { cooldown: 0.13, volleys: 9, columns: 3, width: 14, label: '同時弾 9発' },
  { cooldown: 0.13, volleys: 9, columns: 3, width: 15, label: '弾が太くなった' },
  { cooldown: 0.12, volleys: 9, columns: 3, width: 15, label: '連射が速くなった' },
  { cooldown: 0.12, volleys: 10, columns: 3, width: 15, label: '同時弾 10発' },
  { cooldown: 0.12, volleys: 10, columns: 3, width: 16, label: '弾が太くなった' },
  { cooldown: 0.11, volleys: 10, columns: 3, width: 16, label: '連射が速くなった' },
  { cooldown: 0.11, volleys: 11, columns: 3, width: 16, label: '同時弾 11発' },
  { cooldown: 0.10, volleys: 11, columns: 3, width: 16, label: '最大出力' },
];
export function loadout(level) { return { ...UPGRADES[Math.max(0, Math.min(UPGRADES.length - 1, Math.floor(level) - 1))] }; }
