import test from 'node:test';
import assert from 'node:assert/strict';
import { createGame, step, snapshot, autoInput } from '../lib/game.js';
import { mulberry32 } from '../lib/rng.js';
const run=(s,seconds,input={},rng=()=>.99)=>{for(let i=0;i<Math.round(seconds*60);i++)s=step(s,1/60,input,rng);return s;};
test('emptyとpausedでは進まない',()=>{for(const status of ['empty','paused','over']) {const s=createGame(status);assert.equal(step(s,.02,{fire:true}),s);}});
test('入力状態を破壊しない',()=>{const s=createGame('playing');step(s,.02,{fire:true});assert.equal(s.bullets.length,0);assert.equal(s.time,0);});
test('左右移動を画面に収める',()=>{let s=run(createGame('playing'),2,{left:true});assert.equal(s.player.x,24);s=run(s,2,{right:true});assert.equal(s.player.x,456);});
test('同時2発・250ms間隔・速さ860',()=>{let s=step(createGame('playing'),.01,{fire:true},()=>.99);assert.equal(s.bullets[0].y,568-8.6);s=run(s,.2,{fire:true});assert.equal(s.bullets.length,1);s=run(s,.05,{fire:true});assert.equal(s.bullets.length,2);for(let i=0;i<120;i++){s=step(s,1/60,{fire:true},()=>.99);assert.ok(s.bullets.length<=2);}});
test('初期位置から最初の1隻を落とせる',()=>{for(const seed of [1,2,3,20260921]) {const s=run(createGame('playing'),.7,{fire:true},mulberry32(seed));assert.ok(s.score>=10);}});
test('熱の低い発射は2倍得点',()=>{let s=createGame('playing');s.fleet.enemies.forEach(e=>e.alive=false);const e=s.fleet.enemies[21];e.alive=true;s.bullets=[{x:e.x-2,y:e.y+10,w:4,h:16,bonus:true}];s=step(s,.01,{});assert.equal(s.score,70);assert.equal(s.kills,1);assert.equal(s.bonusKills,1);});
test('熱いレーンはひるみ、150ms後に戻り700msは再発動不可',()=>{let s=createGame('playing');s.shotHeat[6]=6;s=step(s,.01,{fire:true},()=>0);assert.equal(Math.abs(s.fleet.offset),16);s.bullets=[];s.shotCooldown=0;s=run(s,.2,{});assert.equal(s.fleet.offset,0);s=step(s,.01,{fire:true},()=>0);assert.equal(s.fleet.offset,0);});
test('200msごとに居場所が蓄積',()=>{const s=run(createGame('playing'),1);assert.equal(s.positions.length,5);assert.ok(Math.abs(s.predictedX-264)<1e-10);});
test('被弾でライフ減少、1.2秒艦隊停止、復帰',()=>{let s=createGame('playing');s.enemyBullets=[{x:264,y:584,w:6,h:12,vx:0,vy:0}];s=step(s,.01,{});assert.equal(s.lives,2);assert.equal(s.invincible,1.2);const f=s.fleet.x;s=run(s,1,{});assert.equal(s.fleet.x,f);assert.equal(s.lives,2);s=run(s,.3,{});assert.equal(s.invincible,0);});
test('ライフ0で終了',()=>{let s=createGame('playing');s.lives=1;s.enemyBullets=[{x:264,y:584,w:6,h:12,vx:0,vy:0}];assert.equal(step(s,.01,{}).status,'over');});
test('侵入でも終了',()=>{let s=createGame('playing');s.fleet.y=368;assert.equal(step(s,.01,{}).status,'over');});
test('全滅で報酬、1.5秒の空白、その後35隻と3秒の猶予',()=>{let s=createGame('playing');s.fleet.enemies.forEach(e=>e.alive=false);s=step(s,.01,{});assert.equal(s.wave,2);assert.equal(s.score,50);assert.equal(s.waveTransition,1.5);assert.equal(s.floats.at(-1).text,'ウェーブ1 クリア +50');assert.deepEqual(s.events,['wave']);s=run(s,1.4,{fire:true});assert.equal(s.fleet.enemies.filter(e=>e.alive).length,0);assert.equal(s.enemyBullets.length,0);s=run(s,.1);assert.equal(s.fleet.enemies.filter(e=>e.alive).length,35);assert.equal(s.waveTime,0);s=run(s,3);assert.equal(s.enemyBullets.length,0);s.fleet.enemies.forEach(e=>e.alive=false);s=step(s,.01);assert.equal(s.score,150);});
test('敵弾は現在地でなく履歴を狙う',()=>{let s=createGame('playing');s.positions=Array(50).fill(40);s.player.x=450;s.waveTime=3;s.enemyClock=1.7;s=step(s,.01,{},()=>.99);assert.ok(s.enemyBullets[0].vx<0);assert.equal(s.predictedX,40);});
test('snapshotは書き換えても本体を変えない',()=>{const s=createGame();const p=snapshot(s);p.fleet.offset=99;p.heat[0]=1;assert.equal(s.fleet.offset,0);assert.equal(s.heat[0],0);});
test('自動操縦は固定seedで再現し18秒遊べる',()=>{const play=()=>{let s=createGame('playing'),rng=mulberry32(20260921);for(let i=0;i<1080;i++)s=step(s,1/60,autoInput(s),rng);return s;};const s=play();assert.deepEqual(s,play());assert.ok(s.score>0);assert.equal(s.status,'playing');});

test('開幕3秒は敵弾0、その後1.7秒間隔',()=>{let s=run(createGame('playing'),3);assert.equal(s.enemyBullets.length,0);s=run(s,1.65);assert.equal(s.enemyBullets.length,0);s=run(s,.05);assert.equal(s.enemyBullets.length,1);s=run(s,1.7);assert.equal(s.enemyBullets.length,2);});
test('敵弾の速度と波ごとの狙いのばらつき',()=>{for(const wave of [1,2,3,8])for(const random of [0,.5,.999]){let s=createGame('playing');s.wave=wave;s.waveTime=3;s.enemyClock=2;s=step(s,.01,{},()=>random);const b=s.enemyBullets[0];assert.ok(Math.abs(Math.hypot(b.vx,b.vy)-(170+18*wave))<1e-9);const x=b.x-b.vx*.01,y=b.y-b.vy*.01;const target=x+(s.player.y-y)*b.vx/b.vy;assert.ok(Math.abs(target-(s.predictedX+(random*2-1)*Math.max(10,70-20*(wave-1))))<1e-9);}});
test('3波から2回に1回24pxひるむ',()=>{for(const wave of [1,2,3,4]){let s=createGame('playing');s.wave=wave;for(let n=1;n<=4;n++){s.bullets=[];s.shotCooldown=0;s.fleet.flinchCooldown=0;s=step(s,.01,{fire:true},()=>0);assert.equal(Math.abs(s.fleet.offset),wave>=3&&n%2===0?24:16);}}});
test('実発射8回で60以上、移動射撃と時間経過で低下',()=>{let s=createGame('playing'),shots=0;while(shots<8){s=step(s,1/60,{fire:true},()=>.99);if(s.events.includes('fire'))shots++;}assert.ok(s.readLevel>=60);const high=s.readLevel;for(let i=0;i<240;i++)s=step(s,1/60,{targetX:Math.floor(i/60)%2?456:24,fire:true},()=>.99);assert.ok(s.readLevel<high);const heat=Math.max(...s.heat);s=run(s,1);assert.ok(Math.max(...s.heat)<heat);});
test('自動操縦は猶予中中央寄り、380pxから回避、6秒でライフ維持',()=>{let s=createGame('playing');assert.ok(autoInput(s).targetX>=192&&autoInput(s).targetX<=288);s.waveTime=4;s.enemyBullets=[{x:264,y:381}];assert.equal(autoInput(s).targetX,179);s=createGame('playing');const rng=mulberry32(20260921);for(let i=0;i<360;i++)s=step(s,1/60,autoInput(s),rng);assert.equal(s.lives,3);});

test('ウェーブ通過の浮き文字は1件だけ',()=>{let s=createGame('playing');s.floats=[{x:100,y:400,life:.9,text:'+30'},{x:200,y:300,life:.5,text:'裏をかいた ×2'}];s.fleet.enemies.forEach(e=>{e.alive=false;});s=step(s,.01,{});assert.equal(s.floats.length,1);assert.equal(s.floats[0].text,'ウェーブ1 クリア +50');assert.equal(s.floats[0].y,250);});
test('▽の意味は4秒以降に重なった最初の1回だけ',()=>{const hinted=s=>s.floats.some(f=>f.text==='▽ ここを狙われている');let s=run(createGame('playing'),3.9);assert.equal(s.aimHintShown,false);assert.equal(hinted(s),false);s=run(s,.2);assert.equal(s.aimHintShown,true);const hint=s.floats.find(f=>f.text==='▽ ここを狙われている');assert.ok(hint.y<=535&&hint.y>500);s=run(s,1.6);assert.equal(hinted(s),false);s=run(s,2);assert.equal(hinted(s),false);});
